### ISSUE TITLE
[Bug] Default function parameters are not type checked

### ISSUE THREAD

**Issue by dosisod** [beartype/beartype#154]
```python
from beartype import beartype

@beartype
def f(x: str = 1) -> None:
    print(f"called with type {type(x)}")

f()
f(1)
```

Produces the following:

```
$ python3 main.py
called with type <class 'int'>
Traceback (most recent call last):
  File "/home/loot/code/py/beartype/main.py", line 26, in <module>
    f(1)
  File "<@beartype(__main__.f) at 0x7fa35e986050>", line 22, in f
  File "file/.venv/lib/python3.10/site-packages/beartype/_decor/_error/errormain.py", line 301, in raise_pep_call_exception
    raise exception_cls(  # type: ignore[misc]
beartype.roar.BeartypeCallHintParamViolation: @beartyped f() parameter x=1 violates type hint <class 'str'>, as 1 not instance of str.
```

I would expect that both calls would fail, but alas, the first one is allowed through.

**Comment by leycec** [comment]
**Oh, Gods.** You're right. It's true. @beartype is failing us all here.

Happily, I've just realized that we can (and should) be type-checking default parameters **at decoration time.** Rather than wastefully recheck default parameters at call time (i.e., on every repeated call to a decorated callable), @beartype can instead check the default parameters of a decorated callable exactly once when that callable is initially decorated. This has a number of profound benefits, including:

* **It's ludicrously fast.** After all, isn't that why we're all here? Yes. Yes, it is.
* **It's ludicrously early** (i.e., at app startup rather than during app execution). So, @beartype will raise type-checking errors for default parameters *immediately.* That pushes @beartype even closer to the behaviour of a static type-checker, which seems mostly beneficial.

Thanks for the tremendous heads up, @dosisod. This is a critical oversight on our part. We'll bang this out in time for our upcoming `beartype 0.11.0` release.

**Comment by leycec** [comment]
**...lolbro.** I literally cannot believe it took a year-and-some-change for @beartype to type-check defaults. Actually, what am I saying? Of course I can believe it. It's just that... *I don't want to believe it.* :disappointed: 

In other words, @beartype now efficiently type-checks parameter defaults at decoration time. This:

```python
from beartype import beartype

@beartype
def f(x: str = 1) -> None:
    print(f"called with type {type(x)}")

f()
```

...now raises the expected violation:

```python
beartype.roar.BeartypeDoorHintViolation: Function __main__.f() parameter "x"
default value 1 violates type hint <class 'str'>, as int 1 not instance of str.
```

For the sake of my fragile ego, let's pretend I did this within days rather than years. Rejoice, everybody! :smiling_face_with_tear:

**Comment by JWCS** [comment]
I've noticed (in some other responses) you tentatively laying out a roadmap / feature map for 0.19.0, 0.20.0, ...
While taken in jest (who knows what kind of crazy breaking high priority issue is going to suddenly appear?), perhaps organizing open issues & hanging features into github projects might help?

Since there's only one developer (rip), there doesn't need to be much planning (perfect communication + bottleneck), and the number of issues is fairly small, this is probably excessive.
But we stopped having a great idea of what's broken, not implemented (since so much is implemented), what is the great stream of TODOs and false release date promises (add 1.5 years), etc etc etc since ye olde megathread (several GB) was (thankfully) closed.

**Comment by leycec** [comment]
> there's only one developer (rip)

Do you ever feel like the emaciated spectre of Death is looming over your shoulder while grinning cynically at your cats?

> what's broken

**Nuffin'.** This is the answer, @JWCS. Nothing is broken, because you can't break something that never worked in the first place. *Galaxy-brain 4D checkmate.* `<points_knowingly_at_forehead/>`

![](https://media1.tenor.com/m/auEzNCRP64cAAAAd/johan-johan-liebert.gif)

> false release date promises (add 1.5 years)

![](https://media1.tenor.com/m/BqAFY4gNinQAAAAC/batman-dcau.gif)

In all seriousness, the @beartype timetable is *basically* now just:

* **2024:** deeply type-check everything in `O(1)` time.
* **2025:** deeply type-check everything in `O(n)` time under `BeartypeConf(strategy=BeartypeStrategy.On)` configurations.

Of course, we *could* GitHub Project that. Of course, I'd blindly ignore that GitHub Project and then chaotically do whatever I wanted without rhyme or reason. Despite planning, nothing changes.

@beartype is more of a "random walk across the heterogenous `typing` landscape" than a coherent project at this point. Actually, wasn't @beartype *always* pure unadulterated chaos? I'm pretty sure it was. It's a marvel that this creaky zeppelin never ignited under the sheer weight of its unplanned hubris. *How is this thing still flying!?*

Also, I'm pretty sure we now have the working title for my first paper:

* "**Beartype:** A Random Walk Across the Heterogenous `typing` Landscape (5 QA Tips Guido Doesn't Want *You* to Know)."

**Comment by leycec** [comment]
**Resolved by 0fccdb4cb14038a.** This is how the `beartype 0.18.0` cycle ends. Not with a whimper... but a bipedal fat cat miraculously standing guard before your dev machine! Praise be to Fat Cat. Do not fear Fat Cat. Fat Cat only serves Man. <sup>*...for dinner*</sup>

![](https://media1.tenor.com/m/lP0bw19omAIAAAAC/cat-fat.gif)
<sup>how how is this cat still standing</sup>

**Comment by leycec** [comment]
*lolbro.* Much like that "adorable" cat, this didn't quite work out as expected. Let's just quietly reopen this feature request and pretend that @leycec's initial attempt actually worked rather than blowing up the entire @beartype ecosystem. See also related issue #354.

I weep for that cat. I weep! :sob:
