### ISSUE TITLE
[Feature Request] FastAPI integration (if feasible... but probably infeasible)

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [beartype/beartype#250]
Hi @leycec , I found an issue and decided to make an issue out of it rather than to put it in the very long hook thread.

```
 ⚡  /projects/open_source/test_beartype  python -V
Python 3.10.10
 ⚡  /projects/open_source/test_beartype  pip freeze | grep beartype
beartype @ git+https://github.com/beartype/beartype.git@2b8c6823742c29f76ead1222ad08983082792b02
```

```python
# dada.py

from typing import TypeVar
from collections.abc import Iterator
from fastapi import Depends, FastAPI

Self = TypeVar("Self")


class SomeClass:
    @classmethod
    def my_iterator(cls: type[Self]) -> Iterator[Self]:
        yield cls()


app = FastAPI()


@app.get("/items/", response_model=None)
async def read_items(my_value: SomeClass = Depends(SomeClass.my_iterator)) -> int:
    assert isinstance(my_value, SomeClass)
    return 1
```

```python
# dodo.py

import beartype.claw
beartype.claw.beartype_packages(["dada"])

from dada import app
from fastapi.testclient import TestClient

test_client = TestClient(app)

test_client.get("/items")
```

```
 ✘ ⚡  /projects/open_source/test_beartype  python dodo.py
Traceback (most recent call last):
  File "/projects/open_source/test_beartype/dodo.py", line 11, in <module>
    test_client.get("/items")
  File "/opt/conda/lib/python3.10/site-packages/starlette/testclient.py", line 499, in get
    return super().get(
  File "/opt/conda/lib/python3.10/site-packages/httpx/_client.py", line 1041, in get
    return self.request(
  File "/opt/conda/lib/python3.10/site-packages/starlette/testclient.py", line 465, in request
    return super().request(
  File "/opt/conda/lib/python3.10/site-packages/httpx/_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/opt/conda/lib/python3.10/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
  File "/opt/conda/lib/python3.10/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/opt/conda/lib/python3.10/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/opt/conda/lib/python3.10/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "/opt/conda/lib/python3.10/site-packages/starlette/testclient.py", line 342, in handle_request
    raise exc
  File "/opt/conda/lib/python3.10/site-packages/starlette/testclient.py", line 339, in handle_request
    portal.call(self.app, scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/anyio/from_thread.py", line 283, in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
  File "/opt/conda/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.10/site-packages/anyio/from_thread.py", line 219, in _call_func
    retval = await retval
  File "/opt/conda/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/conda/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/conda/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/opt/conda/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/opt/conda/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/projects/open_source/test_beartype/dada.py", line 21, in read_items
    assert isinstance(my_value, SomeClass)
AssertionError
```

If I comment `beartype.claw.beartype_packages(["dada"])` then the script works normally.

Thanks for all your work!

**Comment by gabrieldemarmiesse** [comment]
Thanks for the clarification! I'll open an issue on their side :)

**Comment by gabrieldemarmiesse** [comment]
https://github.com/tiangolo/fastapi/discussions/9885 hopefully it can be fixed on their side

**Comment by leycec** [comment]
Thanks so much for all that! As always, you persist in greatness.

Incidentally, I've given this some much-needed thought while peddling through the backwoods and leech-infested swamplands of Canada *and*... we're probably to blame for your `beartype.roar.BeartypeDecorHintPep585DeprecationWarning` concerns, which you reported elsewhere and I am confusingly discussing here. Specifically, would you mind trying the following as a temporary issue resolution on your end?

* Replace `beartype.roar.BeartypeDecorHintPep585DeprecationWarning` with `beartype.roar._roarwarn.BeartypeDecorHintPep585DeprecationWarning`. The former is only a "fake" name for that warning; the latter is the actual fully-qualified name of that warning. If you specify the latter rather than the former, it's likely that @beartype will begin working as you expect.
 
If that *does* temporarily resolve your issue, would you additionally mind submitting yet another issue? I know exactly how to properly resolve this on our end – but I'd kinda rather not go there unless this is actually our fault.

*Annnnnnyway!* Thanks so much for all the hard-hitting QA. `beartype.claw` is within our grasp. Feel the power of the :bear:.

**Comment by gabrieldemarmiesse** [comment]
For future readers, the original question was here: https://github.com/beartype/beartype/issues/251
I'll answer there
