### ISSUE TITLE
[Bug] beartype.claw doesn't supress warning and exceptions about non pure-python functions

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [beartype/beartype#252]
from https://github.com/beartype/beartype/issues/251#issuecomment-1636671659

>Gah! Really? That's definitely yet another heinous bug you have uncovered. beartype.claw should only ever decorate pure-Python callables. beartype.claw should never attempt to decorate C-based callables. If that's happening, that's bad.

>Would you mind opening up yet another issue with a minimal reproducible example (MRE) I can idly hack on this weekend? If so, thanks so much! If not... it's still "thanks so much!" Let's all rest easy this weekend and play video games.

I am so sorry about your weekend 😢  if that makes you feel better every hour I'm spending beta testing `beartype.claw` is an hour not spend on Persona 5 Royal, so you're not alone

```bash
$ pip freeze | grep beartype
beartype @ git+https://github.com/beartype/beartype.git@163861489c786b5a3dad240cb84bce947600492a
$ pip freeze | grep pydantic
pydantic==1.10.11
```

```python
# dada.py

from pydantic import BaseModel


class MyModel(BaseModel):
    a: int = 1
```

```python
# dodo.py

import beartype.claw
from beartype import BeartypeConf

beartype.claw.beartype_packages(
    ["dada"],
    conf=BeartypeConf(warning_cls_on_decorator_exception=None)
)

from dada import MyModel
```

```
$ python dodo.py
Traceback (most recent call last):
  File "/projects/open_source/test_beartype/dodo.py", line 11, in <module>
    from dada import MyModel
  File "/projects/open_source/test_beartype/dada.py", line 6, in <module>
    class MyModel(BaseModel):
  File "/opt/conda/lib/python3.10/site-packages/beartype/_decor/_cache/cachedecor.py", line 130, in beartype_confed
    return beartype_object(obj, conf)
  File "/opt/conda/lib/python3.10/site-packages/beartype/_decor/decorcore.py", line 95, in beartype_object
    _beartype_object_fatal(obj, conf, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/beartype/_decor/decorcore.py", line 170, in _beartype_object_fatal
    return _beartype_type(  # type: ignore[return-value]
  File "/opt/conda/lib/python3.10/site-packages/beartype/_decor/decorcore.py", line 505, in _beartype_type
    attr_value_beartyped = beartype_object(
  File "/opt/conda/lib/python3.10/site-packages/beartype/_decor/decorcore.py", line 95, in beartype_object
    _beartype_object_fatal(obj, conf, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/beartype/_decor/decorcore.py", line 211, in _beartype_object_fatal
    return beartype_descriptor_decorator_builtin(  # type: ignore[return-value]
  File "/opt/conda/lib/python3.10/site-packages/beartype/_decor/_decormore.py", line 290, in beartype_descriptor_decorator_builtin
    func_checked = beartype_func(func=descriptor.__func__, **kwargs) # type: ignore[union-attr]
  File "/opt/conda/lib/python3.10/site-packages/beartype/_decor/_decormore.py", line 107, in beartype_func
    bear_call.reinit(func, conf, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/beartype/_check/checkcall.py", line 318, in reinit
    self.func_wrappee_codeobj = get_func_codeobj(
  File "/opt/conda/lib/python3.10/site-packages/beartype/_util/func/utilfunccodeobj.py", line 127, in get_func_codeobj
    die_unless_func_python(func=func, exception_cls=exception_cls)
  File "/opt/conda/lib/python3.10/site-packages/beartype/_util/func/utilfunctest.py", line 156, in die_unless_func_python
    raise exception_cls(
beartype.roar.BeartypeDecorWrappeeException: <cyfunction pydantic_encoder at 0x7f6a4d7b8110> not pure-Python function.
```

**Comment by leycec** [comment]
**Ugh! Guh! Barf!** Thanks so much for the weekend deep dive. This traceback is *extremely* interesting in that "My face hurts, Mommy" sort of way. The `pydantic.BaseModel` superclass appears to define a static method possibly named `pydantic_encoder()` wrapping a Cythonized C-based function definitely named `pydantic_encoder()`.

I... didn't know that something so awful could happen. Previously, @beartype assumed that all static methods, class methods, and properties necessarily wrapped pure-Python functions. Clearly, assumptions like this are why `beartype.claw` is still a beautiful but fragile soap bubble that bursts into flames when you actually try to use it.

@beartype is now rethinking all of its life choices. Why have you forsaken us, Shiki-Ouji!?!?

![shiki-ouji forevah](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHsp9d0UDbC8kymyl_5gDmwWk78teD33c7i8aEFdnfNBVVwZtcro4dSPREG6Di2i_PBIY&usqp=CAU)
<sup>...**shiki-ouji:** because the best personas always look like literal trash</sup>

## Tests: We Don't Need No Stinking Tests! Okay. We Do, Actually.

I'm confident I can trivially resolve this in a day or two. I'm less confident I can reliably test that resolution, though. For one, I can't actually replicate this – probably because I'm on the significantly newer Pydantic 2.0.3 and `pydantic-core` 2.3.0, which is now **implemented in Rust.** Yes, I am not kidding. Pydantic has *basically* abandoned Python and gone full-send on Rust. Don't get me wrong: Rust is great. @beartype is partially inspired by Rust. But is Rust-in-Python also great? Five out of ten growling black bears say, "I'd rather eat steaming berries coated in a thick scum of swamp leeches."

**So.** Pydantic ≥ 2.0.0 doesn't exhibit this behaviour. Since Pydantic ≥ 2.0.0 is the obvious future of Pydantic, I'm unclear how to reliably test this in our test suite. Do you have any hot ideas, @gabrieldemarmiesse? Are there *any* other class-based C extensions like `pydantic.BaseModel`? Honestly, I know of none. All the obvious C extensions I know (e.g., NumPy, SciPy, everything in CPython's standard library) just export low-level functions – *not* high-level classes. I am stymied.

Creating C extensions is highly non-trivial and *not* something I'd be inclined to do just to test this unlikely edge case in our test suite. I guess I'll just fix this blindly without actually testing anything. I am Beat Takeshi in *Zatoichi,* blindfolded but still wildly whipping around a deadly sword like I know what I'm doing. This isn't gonna work, is it? :face_exhaling:
