### ISSUE TITLE
[Feature Request] `@beartype` + `@functools.lru_cache` integration

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [beartype/beartype#253]
I'm eating a lot of honey but sometimes I get stung. How can I get honey without any bees???

```python
# trying_stuff_module.py

from functools import lru_cache

@lru_cache(maxsize=3)
def plus_one(n: int) -> int:
    return n +1
```

```python
# trying_stuff_main.py

import beartype.claw

beartype.claw.beartype_packages(["trying_stuff_module"])

from trying_stuff_module import plus_one

print(plus_one(2))
```

```bash
$ python trying_stuff_main.py
/projects/open_source/beartype/beartype/_decor/decorcore.py:414: BeartypeClawDecorWarning: Object trying_stuff_module.plus_one() :
Traceback (most recent call last):
      File "/projects/open_source/beartype/beartype/_decor/decorcore.py", line 367, in _beartype_object_nonfatal
        return _beartype_object_fatal(obj, conf, **kwargs)
      File "/projects/open_source/beartype/beartype/_decor/decorcore.py", line 229, in _beartype_object_fatal
        return beartype_object_monkeypatch(  # type: ignore[return-value]
      File "/projects/open_source/beartype/beartype/_decor/_decormore.py", line 382, in beartype_object_monkeypatch
        obj.__class__.__call__ = _beartype_descriptor_method_bound(  # type: ignore[assignment,method-assign]
      File "/projects/open_source/beartype/beartype/_decor/_decormore.py", line 411, in _beartype_descriptor_method_bound
        assert isinstance(descriptor, MethodBoundInstanceOrClassType), (
    AssertionError: <method-wrapper '__call__' of functools._lru_cache_wrapper object at 0x7f42fb82dc70> not builtin bound method descriptor.

  warn(warning_message, warning_category)
3
```

**Comment by leycec** [comment]
> I'm eating a lot of honey but sometimes I get stung.

:smile: `->` :laughing: `->` :rofl: 

> `AssertionError: <method-wrapper '__call__' of functools._lru_cache_wrapper object at 0x7f42fb82dc70> not builtin bound method descriptor.`

:disappointed: `->` :cry: `->` :sob: 

Thankfully, this should be mostly trivial. It looks like *any* arbitrary object – including low-level C-based private `functools._lru_cache_wrapper` objects – can be a `@functools.wrap` wrapper. That's unexpected, but ultimately fine... and probably a good thing. This means we'll just need to generalize our assumptions about what constitutes a valid **@beartypeable** (i.e., an object that can be decorated by @beartype).

Let's do this. Team Bear-Bear: *Assemble*! :muscle: :man_beard:

**Comment by leycec** [comment]
**So.** It begins. (╯°□°)╯︵ ┻━┻

**Comment by leycec** [comment]
So. It ends. `( ͡° ͜ʖ ͡°)`
