### ISSUE TITLE
[Bug? Maybe?] beartype.claw modifies the stacktrace when an exception unrelated to beartype happens

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [beartype/beartype#254]
```python
# trying_stuff_module.py
def plus_one(n: int) -> int:
    raise ValueError("I crashed :(")
    return n +1
```

```python
# trying_stuff_main.py

import beartype.claw
from beartype import BeartypeConf
beartype.claw.beartype_packages(["trying_stuff_module"])

from trying_stuff_module import plus_one

print(plus_one(2))
```

```bash
$ python trying_stuff_main.py
Traceback (most recent call last):
  File "/projects/open_source/beartype/trying_stuff_main.py", line 13, in <module>
    print(plus_one(2))
  File "<@beartype(trying_stuff_module.plus_one) at 0x7fee0f443880>", line 30, in plus_one
  File "/projects/open_source/beartype/trying_stuff_module.py", line 5, in plus_one
    raise ValueError("I crashed :(")
ValueError: I crashed :(
```
As you can see, beartype is adding a line here. The stacktrace is simple, but for big stacktraces, that adds up a lot!
You can compare with the same stacktrace with the typeguard hook:

```python
# trying_stuff_main.py

import typeguard

typeguard.install_import_hook(["trying_stuff_module"])

from trying_stuff_module import plus_one
print(plus_one(2))
```

```bash
$ python trying_stuff_main.py
Traceback (most recent call last):
  File "/projects/open_source/beartype/trying_stuff_main.py", line 13, in <module>
    print(plus_one(2))
  File "/projects/open_source/beartype/trying_stuff_module.py", line 5, in plus_one
    raise ValueError("I crashed :(")
ValueError: I crashed :(
```

The line `  File "<@beartype(trying_stuff_module.plus_one) at 0x7fee0f443880>", line 30, in plus_one` is not present, making the stacktrace clearer.

**Comment by leycec** [comment]
**Excellent request...** as always. On the one hand, I *definitely* see the pragmatic utility in what you're proposing. On the other hand, I generally side with [PEP 20 – The Zen of Python](https://peps.python.org/pep-0020) in all things:

> Explicit is better than implicit.

That is to say, it's largely a good thing that @beartype is explicit, open, and honest about calls to @beartype-generated wrapper functions on the call stack – including in exception tracebacks. It's best that @beartype *not* lie about this unless explicitly asked to lie about this. I politely disagree with `typeguard` on that point. Of course, you're *not* wrong (and neither is `typeguard`); for some use cases, those calls could be regarded as a spurious distraction that inhibits debuggability and readability.

All of which is to say... **let's add a new `BeartypeConf.is_beartype_in_violation_traceback: bool = True` parameter.** For both conformance with PEP 8 *and* consistency with prior @beartype versions, this parameter will (probably) preserve our existing behaviour by defaulting to `True`. You and your wonderful team of forward-thinking awesome devs would then quietly shake your collective heads and just set this parameter to `False`.
