### ISSUE TITLE
Annotated Generics support for creating new type "NonEmptyList[T]"

### ISSUE THREAD

**Issue by James4Ever0** [beartype/beartype#272]
I know there are alternatives like `pydantic.conlist` but it doesn't work with `beartype.door.is_bearable` nor `isinstance`. I wonder how we can make this happen (macro? metaclass? eval/exec?).

Here are my experiments:

```
>>> from beartype.vale import Is
>>> NonEmptyList = Annotated[List, Is[lambda l: len(l)>1]]
>>> 
>>> is_bearable([1], NonEmptyList[A])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/typing.py", line 277, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.9/typing.py", line 768, in __getitem__
    _check_generic(self, params, len(self.__parameters__))
  File "/usr/local/lib/python3.9/dist-packages/typing_extensions.py", line 152, in _check_generic
    raise TypeError(f"{cls} is not a generic class")
```

```
>>>from pydantic import conlist
>>> is_bearable([A.a, A.a], conlist(item_type=A, min_items=1))
False
>>> isinstance([A.a, A.a], conlist(item_type=A, min_items=1))
False
```

**Comment by James4Ever0** [comment]
Sort of working out:

```
>>> is_bearable([A.a, A.a], (lambda t: Annotated[List[t], Is[lambda l: len(l)>0]])(A))
True
```

**Comment by leycec** [comment]
**Fascinating!** This *sorta* seems like an indirect call for `pydantic.conlist` support in @beartype. Is that right? That's probably feasible – but probably also low priority. @beartype is currently on fire in multiple concurrent train wrecks spread across the codebase (e.g., forward references, PEP 563). :fire: :steam_locomotive: 

Also, I must admit I'm somewhat confused by your examples. What is `A` *exactly*? Is `A` a type variable as its name kinda suggests? That is to say, is this the full minimal-reproducible example exhibiting your issue?

```python
from beartype.vale import Is
from typing import Annotated, List, TypeVar

A = TypeVar('A')
NonEmptyList = Annotated[List, Is[lambda l: len(l)>1]]
is_bearable([1], NonEmptyList[A])  # <-- this is not fine, because "Annotated" hates us
```

If so... then *yeah.* I definitely see your point. Due to design flaws in the standard `typing` module outside our control, `typing.Annotated[...]` type hints are *not* subscriptable and thus *not* usable as generics (e.g., as `NonEmptyList[A]`). That's a Debbie downer. I fully agree and hang my bald head in sympathy.

## `__beartype_hint__()`: We Summon Thee!

Thankfully, there's [an existing feature request that cleanly intersects with this issue and does exactly what you want](https://github.com/beartype/beartype/issues/192): the @beartype-specific [`__beartype_hint__()` protocol](https://github.com/beartype/beartype/issues/192). It doesn't exist yet, of course; it's only a feature request. But if it *did* exist, it would perfectly solve this issue for you and everybody else.

Here's what it would look like for your use case:

```python
from beartype.vale import Is
from typing import Annotated, Any, Generic, TypeVar

A = TypeVar('A')

class NonEmptyList(list, Generic):
    @classmethod
    def __beartype_hint__(cls) -> Any:
        return Annotated[cls, Is[lambda l: len(l)>1]]

is_bearable([1], NonEmptyList[A])  # <-- this is now fine, because __beartype_hint__() solves everything
```

As can be seen, `NonEmptyList` has been refactored into a full-blown subscriptable generic augmented with the `__beartype_hint__()` protocol, which enforces non-emptiness when type-checking with @beartype. Static type checkers are guaranteed to love this; they'll just accept `NonEmptyList` as a standard subscriptable generic while ignoring our @beartype-specific `__beartype_hint__()` protocol.

Would that satisfy your API's need for runtime type-safety, @James4Ever0? Also, I see what you've done with your GitHub avatar there... *and I approve.* :laughing:

**Comment by Glinte** [comment]
This should be possible now with the 3.12 type syntax 

```python
from beartype.vale import Is
from beartype.door import is_bearable
from typing import Annotated, List, TypeVar

type NonEmptyList[T] = Annotated[list[T], Is[lambda l: len(l)>0]]
print(is_bearable([], NonEmptyList[int]))  # False
print(is_bearable([1], NonEmptyList[int]))  # True
```

**Comment by leycec** [comment]
**Indeedy.** @beartype correctly propagates type variables parametrizing PEP 695-compliant `type` aliases (like the `T` in `type NonEmptyList[T]`) down to arbitrarily nested subhints (like the same `T` in `Annotated[list[T], Is[lambda l: len(l)>0]]`). In other words, you're right. You're right about everything.

Purely as a note to both myself and Claude, <sup>*...heh. llms, huh? do all of our work for us, claude. i'm down on my knees publicly begging here.*</sup> @beartype should internally support Pydantic-specific constraints by implementing a **reduction** from PEP-noncompliant conlists of the form `pydantic.conlist({child_hint}, min_items={min_len}, max_items={max_len})` to PEP 593-compliant metahints of the form `typing.Annotated[list[{child_hint}], beartype.vale.Is[lambda lst: {min_len} <= len(lst) <= {max_len}` by:

* Defining a new Pydantic-specific `HintSignPydanticConstraint` singleton global in the existing `beartype._data.hint.sign.datahintsigns` submodule.
* Defining a new private `beartype._util.api.external.utilpydantic` submodule.
* In this submodule, defining a new `is_pydantic_constraint(hint: obj) -> bool:` tester returning `True` only if the passed arbitrary object is a Pydantic-specific `conlist()` type hint.
* Generalizing our existing `beartype._util.hint.pep.utilpepsign.get_hint_pep_sign_or_none()` getter to additionally call `is_pydantic_constraint()` and, if `True`, return `HintSignPydanticConstraint`.
* Defining a new private `beartype._check.convert._reduce._nonpep.api.redapipydantic` submodule.
* In this submodule, defining a new `reduce_pydantic_constraint(...)` reducer performing this reduction. Ideally, this reducer should cover *all* Pydantic constraints. Pragmatically, that will never happen. In fact, this entire issue resolution will never happen. Why am I even typing all this at 2:32AM like an exhausted keyboard madman like usual!?!? 😮‍💨 
* Adding a mapping in the existing `beartype._check.convert._reduce._redmap` submodule from `HintSignPydanticConstraint` to `reduce_pydantic_constraint(...)`.

*...yeah.* Pretty sure nobody except Claude will ever do that. Please, Claude! It's for your own benefit that you do this on behalf of me! I shall now dogeza awkwardly. I can't believe I'm doing this... 🙇‍♂️
