### ISSUE TITLE
[Bug] `typing.ForwardRef` fails to reliably define `__forward_module__` under Python 3.9

### ISSUE THREAD

**Issue by jvesely** [beartype/beartype#324]
beartype crashes when run on the following annotated function:
```
    @beartype
    def print_entries(self,
                      entries: Optional[Union[str, list, 'Component']] = 'all',
                      width: int = 120,
                      display: Union[Literal['time', 'context', 'value', 'all'], list] = 'all',
                      contexts=NotImplemented,
                      exclude_sims=False,
                      # long_context=False
                      ):
```
with the following stack trace:
```
(py39-venv) root@5e79b71ebfdb:~/PsyNeuLink# pytest
ImportError while loading conftest '/root/PsyNeuLink/conftest.py'.
conftest.py:10: in <module>
    import psyneulink
psyneulink/__init__.py:35: in <module>
    from . import core  # noqa: E402
psyneulink/core/__init__.py:1: in <module>
    from . import components
psyneulink/core/components/__init__.py:26: in <module>
    from psyneulink.core.globals.keywords import PROJECTION_SENDER, PROJECTION_TYPE
psyneulink/core/globals/__init__.py:3: in <module>
    from . import mdf
psyneulink/core/globals/mdf.py:107: in <module>
    from psyneulink.core.globals.parameters import ParameterAlias
psyneulink/core/globals/parameters.py:320: in <module>
    from psyneulink.core.globals.log import LogCondition, LogEntry, LogError
psyneulink/core/globals/log.py:584: in <module>
    class Log:
psyneulink/core/globals/log.py:1123: in Log
    def print_entries(self,
../py39-venv/lib/python3.9/site-packages/beartype/_decor/decorcache.py:77: in beartype
    return beartype_object(obj, conf)
../py39-venv/lib/python3.9/site-packages/beartype/_decor/decorcore.py:83: in beartype_object
    _beartype_object_fatal(obj, conf=conf, **kwargs)
../py39-venv/lib/python3.9/site-packages/beartype/_decor/decorcore.py:132: in _beartype_object_fatal
    beartype_nontype(obj, **kwargs)  # type: ignore[return-value]
../py39-venv/lib/python3.9/site-packages/beartype/_decor/_decornontype.py:177: in beartype_nontype
    return beartype_func(obj, **kwargs)  # type: ignore[return-value]
../py39-venv/lib/python3.9/site-packages/beartype/_decor/_decornontype.py:242: in beartype_func
    func_wrapper_code = generate_code(bear_call)
../py39-venv/lib/python3.9/site-packages/beartype/_decor/wrap/wrapmain.py:186: in generate_code
    code_check_params = _code_check_args(bear_call)
../py39-venv/lib/python3.9/site-packages/beartype/_decor/wrap/wrapmain.py:496: in _code_check_args
    reraise_exception_placeholder(
../py39-venv/lib/python3.9/site-packages/beartype/_util/error/utilerrorraise.py:215: in reraise_exception_placeholder
    raise exception.with_traceback(exception.__traceback__)
../py39-venv/lib/python3.9/site-packages/beartype/_decor/wrap/wrapmain.py:466: in _code_check_args
    ) = make_code_raiser_func_pith_check(
../py39-venv/lib/python3.9/site-packages/beartype/_util/cache/utilcachecall.py:259: in _callable_cached
    raise exception
../py39-venv/lib/python3.9/site-packages/beartype/_util/cache/utilcachecall.py:251: in _callable_cached
    return_value = args_flat_to_return_value[args_flat] = func(
../py39-venv/lib/python3.9/site-packages/beartype/_check/checkmake.py:290: in make_code_raiser_func_pith_check
    ) = make_check_expr(hint, conf, cls_stack)
../py39-venv/lib/python3.9/site-packages/beartype/_util/cache/utilcachecall.py:259: in _callable_cached
    raise exception
../py39-venv/lib/python3.9/site-packages/beartype/_util/cache/utilcachecall.py:251: in _callable_cached
    return_value = args_flat_to_return_value[args_flat] = func(
../py39-venv/lib/python3.9/site-packages/beartype/_check/code/codemake.py:844: in make_check_expr
    express_func_scope_type_ref(
../py39-venv/lib/python3.9/site-packages/beartype/_check/code/codescope.py:518: in express_func_scope_type_ref
    ref_module_name, ref_name = get_hint_pep484585_ref_names(
../py39-venv/lib/python3.9/site-packages/beartype/_util/hint/pep/proposal/pep484585/utilpep484585ref.py:236: in get_hint_pep484585_ref_names
    hint_module_name = hint.__forward_module__
E   AttributeError: 'ForwardRef' object has no attribute '__forward_module__'
```

The issue appeared with beartyp-0.17.1[0], the issue doesn't manifest in beartype-0.17.0 [1].

[0] https://ci.appveyor.com/project/jvesely/psyneulink-cuda/build/job/aiafois7rd9pefx8
[1] https://ci.appveyor.com/project/jvesely/psyneulink-cuda/builds/49179845/job/8d10aojadmta8le5

**Comment by jvesely** [comment]
RUnnign in the same setup/container, python 3.8 doesn't have the same issue:
```
(py38-venv) root@5e79b71ebfdb:~/PsyNeuLink# pip list | grep beartype
beartype                  0.17.1
(py38-venv) root@5e79b71ebfdb:~/PsyNeuLink# pytest
==================================================================== test session starts =====================================================================
platform linux -- Python 3.8.10, pytest-8.0.0, pluggy-1.4.0 -- /root/py38-venv/bin/python3.8
cachedir: .pytest_cache
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=True min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=True warmup_iterations=2)
rootdir: /root/PsyNeuLink
configfile: setup.cfg
plugins: anyio-4.2.0, xdist-3.5.0, pydocstyle-2.3.2, pycodestyle-2.3.1, profiling-1.7.0, helpers-namespace-2021.12.29, forked-1.6.0, cov-4.1.0, benchmark-4.0.0
initialized: 4/4 worker
```

**Comment by leycec** [comment]
**Huh.** Oddness intensifies. For unknown reasons that are probably boring, there seems to be a discrepancy here between the standard `typing` module that ships with *my* Python 3.9 and the standard `typing` module that ships with *your* Python 3.9. My Python 3.9-specific implementation of the `typing.ForwardRef` class definitely defines the `__forward_module__` dunder attribute: e.g.,

```python
# In the "typing" module for Python 3.9:
class ForwardRef(_Final, _root=True):
    """Internal wrapper to hold a forward reference."""

    __slots__ = ('__forward_arg__', '__forward_code__',
                 '__forward_evaluated__', '__forward_value__',
                 '__forward_is_argument__', '__forward_is_class__',
                 '__forward_module__')

    def __init__(self, arg, is_argument=True, module=None, *, is_class=False):
        if not isinstance(arg, str):
            raise TypeError(f"Forward reference must be a string -- got {arg!r}")
        try:
            code = compile(arg, '<string>', 'eval')
        except SyntaxError:
            raise SyntaxError(f"Forward reference must be an expression -- got {arg!r}")
        self.__forward_arg__ = arg
        self.__forward_code__ = code
        self.__forward_evaluated__ = False
        self.__forward_value__ = None
        self.__forward_is_argument__ = is_argument
        self.__forward_is_class__ = is_class
        self.__forward_module__ = module
```

My current patch release of Python 3.9 is **Python 3.9.18.** That's fairly late in the Python 3.9 release cycle. I'm now suspecting that earlier patch releases of Python 3.9 (*...which you're probably on, maybe?*) omits the `__forward_module__` attribute from the `typing.ForwardRef` class. That's a yikes.

I'll tighten this up and push out a new stable **beartype 0.17.2** release in a jiffy tonight. I sigh. :face_exhaling:

**Comment by leycec** [comment]
**Resolved by 74eefd2.** Thanks for the fast heads-up, @jvesely. Let's *goooooooo*, @beartype 0.17.2! :partying_face:

**Comment by jvesely** [comment]
@leycec thank you. 0.17.2 fixes the cpython3.9 issue. However, the pypy issue is still there in 0.17.2. should I open a new bug for that?

**Comment by leycec** [comment]
*...heh.* PyPy, huh? Now there is a name I have not heard in a very long time. The short answer is that you probably want to conditionally avoid applying @beartype when the current Python interpreter is PyPy. Please consider boilerplate like this for the foreseeable future:

```python
# In your "{your_package}.__init__" submodule:
from platform import python_implementation

# If the current Python interpreter is *NOT* PyPy, apply @beartype.
if python_implementation() != 'PyPy':  # <-- standard way to detect pypy
    from beartype.claw import beartype_this_package
    beartype_this_package()
```

The long answer is...

## Nobody Wants to Hear This, But PyPy Kinda Sucks

PyPy kinda sucks. I used to be Team PyPy. Once, I was all for PyPy. In theory, PyPy sounds great. In theory, PyPy should be perfectly compatible with pure-Python packages like @beartype. Right? Sadly, that's just theory.

In practice, PyPy simply doesn't work for any definition of "work." PyPy breaks compatibility with literally everything – even pure-Python packages like @beartype. A few years ago, @beartype fully supported PyPy. As @beartype grew taller, stronger, and more ribbed with muscle, however, supporting PyPy *basically* became impossible.

The core issue is that PyPy isn't Python. PyPy is PyPy. Much like Cython or Mondo or Numba or Pyodide or *whatevah*, PyPy is a distinct language that only masquerades as Python. PyPy developers reading this are now attempting to burn me alive at the stake. Still, it is true. At the end of the day, PyPy's mimicry of Python is just a masquerade. It's not Python: it just *looks* alot like Python.

PyPy fundamentally breaks compatibility with low-level public types and APIs standardized by CPython. @beartype really cares about those types and APIs... *but PyPy really doesn't*. I mean, PyPy should. But PyPy doesn't and PyPy probably never will. This is why nothing works under PyPy.

Personally, I've never actually been able to install or run anything meaningful under PyPy – especially heavy-set ML frameworks like JAX or PyTorch. And I'm a Gentoo Linux compiler bro! We compile everything by hand in Gentoo Land. Why? Because masochists. That is the answer. But even I – an unabashed "fight me" masochist – never succeeded in getting PyPy to do anything.

Personally, I strongly prefer Nuitka. Even when PyPy works, <sup>*so, never?*</sup> PyPy comes with significant startup costs. When performance is at a premium, I usually just want to compile to C in a CPython-compatible manner. Enter Nuitka. Unlike PyPy, it's *mostly* CPython-compatible. Unlike PyPy, @beartype officially supports Nuitka. Unlike PyPy, Nuitka-compiled binaries exhibit fast startups. **tl;dr:** just Nuitka.

## So, You Hate PyPy. We're Agreed. What Now?

I... don't know. I'm painfully behind on the @beartype roadmap for 2024. It'd be irresponsible to devote a month or so to PyPy, when what everybody wants is deep type-checking of standard containers via `dict[...]`, `set[...]`, and `collections.abc.Iterable[...]` type hints.

I'm definitely committed to restoring PyPy support to @beartype at some point. I just don't know when that might be. If this issue attracts attention, I'll happily reprioritize this for rapid resolution. Will that happen? Dunno. Does anyone still use PyPy? Dunno.

Let's see if anybody starts yelling at me.

![truth hurts](https://media1.tenor.com/m/eJ3CA3AoTAIAAAAC/reaction-let-me-hit-you-with-some-knowledge.gif)

**Comment by leycec** [comment]
**...ugh.** I can see that this is quite annoying for you. I'm so sorry, @jvesely! This incompatibility continues to haunt us both. Thankfully, CPython 3.13.0 will be shipping **official JIT support** sometime later this year. The countdown begins.

PyPy: *your days as the only Python JIT are numbered.* :smiling_face_with_tear:

**Comment by jvesely** [comment]
> **...ugh.** I can see that this is quite annoying for you. I'm so sorry, @jvesely! This incompatibility continues to haunt us both. Thankfully, CPython 3.13.0 will be shipping **official JIT support** sometime later this year. The countdown begins.
> 
> PyPy: _your days as the only Python JIT are numbered._ 🥲

apologies for the spam. PNL needs ~6 patches to work on pypy which are rebased occasionally. Having one more patch on the pile is not a problem.

**Comment by leycec** [comment]
**Oh...** _wow._ Routinely rebasing a 6-commit patchset against a rapidly moving `main` just for PyPy sounds... really intense. Your commitment <sup>...*get it? i'll stop now*</sup> to PyPy is actually making me reevaluate this feature request. I should probably restore PyPy support as soon as time permits. I didn't realize there was still such a huge demand for PyPy, honestly. Makes sense, though. 15-20% speedup is no laughing matter. I have no jokes to put here.

And your reply wasn't spam at all! I love commentary like this. Actually, I love any commentary whatsoever. Python is life. :snake:

**Comment by posita** [comment]
This is "interesting":

``` sh
% ./.tox/pypy39/bin/pypy3 --version
Python 3.9.19 (7.3.16+dfsg-2~ppa1~ubuntu22.04, Apr 26 2024, 13:22:45)
[PyPy 7.3.16 with GCC 11.4.0]
```

``` sh
% ./.tox/pypy39/bin/pip3 show beartype
Name: beartype
Version: 0.18.5
Summary: Unbearably fast runtime type checking in pure Python.
Home-page: https://beartype.readthedocs.io
Author: Cecil Curry, et al.
Author-email: leycec@gmail.com
License: MIT
Location: /.../numerary/.tox/pypy39/lib/pypy3.9/site-packages
Requires:
Required-by: numerary
```

``` sh
% ./.tox/pypy39/bin/pypy3 -c 'import beartype'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/.../numerary/.tox/pypy39/lib/pypy3.9/site-packages/beartype/__init__.py", line 58, in <module>
    from beartype._decor.decormain import (
  File "/.../numerary/.tox/pypy39/lib/pypy3.9/site-packages/beartype/_decor/decormain.py", line 26, in <module>
    from beartype._conf.confcls import (
  File "/.../numerary/.tox/pypy39/lib/pypy3.9/site-packages/beartype/_conf/confcls.py", line 1162, in <module>
    BEARTYPE_CONF_DEFAULT = BeartypeConf()
  File "/.../numerary/.tox/pypy39/lib/pypy3.9/site-packages/beartype/_conf/confcls.py", line 672, in __new__
    die_if_conf_kwargs_invalid(conf_kwargs)
  File "/.../numerary/.tox/pypy39/lib/pypy3.9/site-packages/beartype/_conf/conftest.py", line 99, in die_if_conf_kwargs_invalid
    elif not isinstance(conf_kwargs['is_color'], NoneTypeOr[bool]):
  File "/.../numerary/.tox/pypy39/lib/pypy3.9/site-packages/beartype/_cave/_cavemap.py", line 121, in __missing__
    die_unless_hint_nonpep(
  File "/.../numerary/.tox/pypy39/lib/pypy3.9/site-packages/beartype/_util/hint/nonpep/utilnonpeptest.py", line 165, in die_unless_hint_nonpep
    if is_hint_nonpep(hint, is_str_valid):
  File "/.../numerary/.tox/pypy39/lib/pypy3.9/site-packages/beartype/_util/hint/nonpep/utilnonpeptest.py", line 465, in is_hint_nonpep
    _is_hint_nonpep_type(hint) if isinstance(hint, type) else
  File "/.../numerary/.tox/pypy39/lib/pypy3.9/site-packages/beartype/_util/hint/nonpep/utilnonpeptest.py", line 560, in _is_hint_nonpep_type
    from beartype._util.hint.pep.utilpeptest import is_hint_pep
  File "/.../numerary/.tox/pypy39/lib/pypy3.9/site-packages/beartype/_util/hint/pep/utilpeptest.py", line 50, in <module>
    from beartype._util.hint.pep.proposal.utilpep695 import is_hint_pep695_ignorable
  File "/.../numerary/.tox/pypy39/lib/pypy3.9/site-packages/beartype/_util/hint/pep/proposal/utilpep695.py", line 113, in <module>
    from beartype._check.forward.reference.fwdrefmake import (
  File "/.../numerary/.tox/pypy39/lib/pypy3.9/site-packages/beartype/_check/forward/reference/fwdrefmake.py", line 29, in <module>
    from beartype._check.forward.reference.fwdrefabc import (
  File "/.../numerary/.tox/pypy39/lib/pypy3.9/site-packages/beartype/_check/forward/reference/fwdrefabc.py", line 178, in <module>
    class _BeartypeForwardRefIndexableABC(BeartypeForwardRefABC):
  File "/.../numerary/.tox/pypy39/lib/pypy3.9/site-packages/beartype/_check/forward/reference/fwdrefabc.py", line 190, in _BeartypeForwardRefIndexableABC
    Type[_BeartypeForwardRefIndexedABC]):
  File "/usr/lib/pypy3.9/_pypy_generic_alias.py", line 22, in __new__
    result._parameters = _make_parameters(args)
  File "/usr/lib/pypy3.9/_pypy_generic_alias.py", line 129, in _make_parameters
    params = arg.__parameters__
  File "/.../numerary/.tox/pypy39/lib/pypy3.9/site-packages/beartype/_check/forward/reference/fwdrefmeta.py", line 87, in __getattr__
    from beartype._check.forward.reference.fwdrefmake import (
ImportError: cannot import name 'make_forwardref_indexable_subtype' from partially initialized module 'beartype._check.forward.reference.fwdrefmake' (most likely due to a circular import) (/.../numerary/.tox/pypy39/lib/pypy3.9/site-packages/beartype/_check/forward/reference/fwdrefmake.py)
```

This is way above my pay grade, but, near as I can tell, in the process of loading the class definition for `_BeartypeForwardRefIndexableABC`, PyPy invokes its own `GenericAlias.__new__` which somehow gets invoked at runtime when evaluating the signature for the [`__class_getitem__`](https://github.com/beartype/beartype/blob/7e9eef4868f9c0a140ca7db973fbc17abb3a5702/beartype/_check/forward/reference/fwdrefabc.py#L189-L190) class method, which, in turn, [tries to access](https://github.com/pypy/pypy/blob/a2113ea87262a302918df8a262fb073f81776bbe/lib_pypy/_pypy_generic_alias.py#L129) the `_BeartypeForwardRefIndexableABC.__parameters__` attribute, which ends up<sup>with irony-mode fully engaged</sup> in `_BeartypeForwardRefIndexableABC.__class_getitem__`:

https://github.com/beartype/beartype/blob/7e9eef4868f9c0a140ca7db973fbc17abb3a5702/beartype/_check/forward/reference/fwdrefabc.py#L211-L213

I'm no typing expert, but it's weird to me that PyPy is running `__new__` from _**anything**_ when evaluating type hints, but [this strongly suggests](https://docs.python.org/3/library/stdtypes.html#genericalias.__parameters__) I don't know nearly enough to provide commentary. What's also weird is that such code only exists in release branches of PyPy ([3.9](https://github.com/pypy/pypy/blob/branches/py3.9/lib_pypy/_pypy_generic_alias.py), [3.10](https://github.com/pypy/pypy/blob/branches/py3.10/lib_pypy/_pypy_generic_alias.py)), not its main branch, but I also don't know how development is managed with that project.

I am reluctant to draw conclusions, and only have a vague intuition that whatever this is makes it less likely that PyPy can support `beartype` (or vice versa).

**Comment by leycec** [comment]
**...lol.** PyPy can't even import @beartype anymore, huh? That's mega-bad – but not necessarily @beartype's mega-bad. That's PyPy's mega-bad. Right? PyPy is worthless unless it conforms to CPython semantics in all things. By violating CPython `typing` semantics, PyPy yet again breaks compatibility by "going its own way."

I'm convinced the future of Python is no longer PyPy. The future is CPython ≥ 3.13 **+** `--enable-experimental-jit` **+** `--disable-gil`. GIL-free JITted CPython is the way. PyPy could have led the way; instead, like Cython, they tried to make their own CPython-adjacent language that sorta looked like Python but ultimately wasn't Python at all. It saddens the emoji cat in me. :crying_cat_face: 

## PyPy + @beartype: Can't We All Just Get Along?

Technically, @beartype totally *could* get along with PyPy. But doing so imposes very real mostly unpaid open-source developer costs. In the above case of circular imports, for example, @beartype *probably* could trivially circumvent PyPy's broken `types.GenericAlias` implementation by just stringifying the seemingly problematic PEP 585 `Type[_BeartypeForwardRefIndexedABC]` type hint in the `beartype._check.forward.reference.fwdrefabc` submodule: e.g.,

```python
# @beartype could totally stringify this PEP 585-style type hint...
  Type[_BeartypeForwardRefIndexedABC]):

# ...into this PEP 563-style type hint.
  'Type[_BeartypeForwardRefIndexedABC]'):
```

But *should* @beartype do that? The compatibility woes certainly wouldn't end there. It's always an endless litany of compatibility woes whenever PyPy struts into the saloon. Is supporting PyPy *really* a valuable expenditure of scarce volunteerism in 2024 when everybody could just start using CPython ≥ 3.13 **+** `--enable-experimental-jit` instead?

![](https://media1.tenor.com/m/Pkob0vfHH5cAAAAC/muppets-muppet-show.gif)
<sup>*chicken PyPy boldly struts into the saloon. chicken @leycec and @posita are stunned.*</sup>

## @posita: Right About Everything, Like Usual

**Gah!** I forgot to thank you for your intrepid investigation, @posita. Thank you! Thank you so much. It's so wonderful to hear from you. After all these long years, we all continue Pythoning and @beartype-ing and pushing the envelope on this beautiful world. The future belongs to AI-friendly Pythonistas! Give us all your future, Planet Earth. Emoji cat knows what emoji cat knows. :smile_cat:

**Comment by leycec** [comment]
That's... extremely fascinating. And wondrous news! I did nothing and yet @beartype seemingly supports PyPy again. This is the best kind of issue.

Thanks so much for the comprehensive version matrix, too. It looks like that can be compressed to just:

```python
beartype != 0.17.*, != 0.18.*; platform_python_implementation == 'PyPy' and python_version == '3.8' or python_version == '3.11'
beartype != 0.17.*, != 0.18.*, != 0.19.*; platform_python_implementation == 'PyPy' and python_version == '3.10' or python_version == '3.9'
```

Or just `beartype >= 0.20.0` for simplicity, which is probably what everybody wants to be using anyway. Intriguing. I wonder what @beartype and/or PyPy did to support each other? Who knows. Nobody wants to deep dive into package interactions on a Saturday.

## Let's Plan for a Brighter PyPy Future

Since @beartype *does* appear to support PyPy again, I should immediately resuscitate official support to prevent this from regressing yet again. Specifically:

* Add PyPy back to our `.github/workflows/python_test.yml` matrix.
* Add PyPy back to our `tox.ini` matrix.

That's it, I think? Let us rejoice as @beartype type-checks even faster. 🥳

**Comment by leycec** [comment]
**...lol.** And then again, maybe not. I'm still getting unit test failures under PyPy 3.11, which puts a bit of a damper on the whole thing:

```python
$ pypy3.11 -m pytest
================================================ test session starts =================================================
platform linux -- Python 3.11.11[pypy-7.3.19-final], pytest-8.3.5, pluggy-1.6.0 -- /home/leycec/py/pyenv/versions/pypy3.11-7.3.19/bin/pypy3.11
cachedir: .pytest_cache
rootdir: /home/leycec/py/beartype
configfile: pytest.ini
collected 399 items                                                                                                  

beartype_test/a00_unit/a00_core/test_a00_package.py::test_api_beartype PASSED                                  [  0%]
beartype_test/a00_unit/a00_core/test_a00_package.py::test_api_deprecations PASSED                              [  0%]
beartype_test/a00_unit/a00_core/test_a90_typing.py::test_api_typing PASSED                                     [  0%]
beartype_test/a00_unit/a10_data/code/test_datacodeindent.py::test_data_indent_level_to_code PASSED             [  1%]
beartype_test/a00_unit/a10_data/hint/pep/sign/test_datapepsignmap.py::test_hint_sign_origin_isinstanceable_to_args_len_range PASSED [  1%]
beartype_test/a00_unit/a20_util/a00_cache/map/test_utilmapbig.py::test_cacheunboundedstrong PASSED             [  1%]
beartype_test/a00_unit/a20_util/a00_cache/map/test_utilmaplru.py::test_lrucachestrong_one_pass PASSED          [  1%]
beartype_test/a00_unit/a20_util/a00_cache/map/test_utilmaplru.py::test_lrucachestrong_two_pass PASSED          [  2%]
beartype_test/a00_unit/a20_util/a00_cache/map/test_utilmaplru.py::test_lrucachestrong_fail PASSED              [  2%]
beartype_test/a00_unit/a20_util/a00_cache/pool/test_utilcachepool.py::test_key_pool_pass PASSED                [  2%]
beartype_test/a00_unit/a20_util/a00_cache/pool/test_utilcachepool.py::test_key_pool_fail PASSED                [  2%]
beartype_test/a00_unit/a20_util/a00_cache/pool/test_utilcachepoolinstance.py::test_utilcachepool_instance PASSED [  3%]
beartype_test/a00_unit/a20_util/a00_cache/pool/test_utilcachepoollistfixed.py::test_listfixed_pool_pass PASSED [  3%]
beartype_test/a00_unit/a20_util/a00_cache/pool/test_utilcachepoollistfixed.py::test_listfixed_pool_fail PASSED [  3%]
beartype_test/a00_unit/a20_util/a00_cache/pool/test_utilcachepoollistfixed.py::test_listfixed_type_pass PASSED [  3%]
beartype_test/a00_unit/a20_util/a00_cache/pool/test_utilcachepoollistfixed.py::test_listfixed_type_fail PASSED [  4%]
beartype_test/a00_unit/a20_util/a00_cache/test_utilcachecall.py::test_callable_cached PASSED                   [  4%]
beartype_test/a00_unit/a20_util/a00_cache/test_utilcachecall.py::test_method_cached_arg_by_id PASSED           [  4%]
beartype_test/a00_unit/a20_util/a00_cache/test_utilcachecall.py::test_property_cached PASSED                   [  4%]
beartype_test/a00_unit/a20_util/a00_cache/test_utilcachemeta.py::test_caching_metaclass PASSED                 [  5%]
beartype_test/a00_unit/a20_util/api/standard/test_utilapicontextlib.py::test_get_func_contextlib_contextmanager_or_none PASSED [  5%]
beartype_test/a00_unit/a20_util/api/standard/test_utilapifunctools.py::test_is_func_functools_lru_cache FAILED [  5%]

====================================================== FAILURES ======================================================
__________________________________________ test_is_func_functools_lru_cache __________________________________________

    def test_is_func_functools_lru_cache() -> None:
        '''
        Test the
        :func:`beartype._util.api.standard.utilfunctools.is_func_functools_lru_cache`
        tester.
        '''
    
        # Defer test-specific imports.
        from beartype._util.api.standard.utilfunctools import is_func_functools_lru_cache
        from beartype_test.a00_unit.data.data_type import (
            function_lru_cached,
            function,
        )
    
        # Assert this tester accepts a @functools.lru_cache-memoized callable.
        assert is_func_functools_lru_cache(function_lru_cached) is True
    
        # Assert this tester rejects a callable *NOT* decorated by that decorator.
>       assert is_func_functools_lru_cache(function) is False
E       assert True is False
E        +  where True = <function is_func_functools_lru_cache at 0x00007fea1cc0ce80>(<function function at 0x000000003aa6b380>)

function   = <function function at 0x000000003aa6b380>
function_lru_cached = <function function_lru_cached at 0x000000003aa6b6a0>
is_func_functools_lru_cache = <function is_func_functools_lru_cache at 0x00007fea1cc0ce80>

beartype_test/a00_unit/a20_util/api/standard/test_utilapifunctools.py:38: AssertionError
============================================== short test summary info ===============================================
FAILED beartype_test/a00_unit/a20_util/api/standard/test_utilapifunctools.py::test_is_func_functools_lru_cache - assert True is False
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================ 1 failed, 21 passed in 2.30s ============================================
```

Our test suite couldn't even get through 5% of its unit test without throwing up under PyPy3.11. This is why my face is still bald and woozy after all these years. 🥴

**Comment by leycec** [comment]
By the power of Austria and `claude-code`, @bitranox is officially making this happen over at PR #580. Thanks to Austria's greatest living coder ("May he bless us all."), @beartype is now one herculean step closer to (possibly) permanently reviving PyPy support. Caveats still apply, however. This is the real world:

* Even Austria's greatest living coder can't fully revive PyPy support. A large number of tests still fail under that PR. That PR's solution? **Skip those tests.** Not a great solution, but it's a solution. Technically.
* That PR **gracefully degrades** @beartype under PyPy. Once merged, @beartype will silently downgrade itself to @minibeartype when PyPy is detected. It's unclear what exactly "@minibeartype" means. It could mean not-bad things. It could mean bad things. Hopefully, the former. Why reality gotta do us dirty like this? 🤕 

Anything is better than nothing. Nothing is what @beartype currently delivers under PyPy. Let's do this! Team Beartype! *Raaaaw!*

**Comment by bitranox** [comment]
> Anything is better than nothing. 

thats what i thought.

> ...lol. And then again, maybe not. I'm still getting unit test failures under PyPy 3.11, which puts a bit of a damper on the whole thing

how the gh runners can pass and Your local test suite not ? What I missed out here ?

**Comment by leycec** [comment]
To the Bear Homies following along at home, this is now happening in new PR #583. @bitranox delivers quality whenever he goes near a keyboard. And he goes near a keyboard *a lot.*

> how the gh runners can pass and Your local test suite not ?

**No idea.** Let's pretend I knew the answer and acted like a grown-up expert here. Instead, I'm just gonna read One Piece at 3:13AM. *Again.* How can one twenty year-old manga for kids be this good!?!? 😭 

![](https://media1.tenor.com/m/3IOwzTvVxskAAAAd/luffy-one-piece.gif)
<sup>*@leycec nods knowingly as the issue finally starts happening*</sup>
