### ISSUE TITLE
Additional context seems to break beartype in certain cases

### ISSUE THREAD

**Issue by Moosems** [beartype/beartype#397]
Breaking example I found in my own usage:
```python
from beartype import beartype
from multiprocessing import Queue
from typing import TypedDict

class SpecialDict(TypedDict):
    pass

class Example:
    @beartype
    def __init__(self, list1: Queue) -> None:
        self.list1: Queue[SpecialDict] = list1

q1: Queue[SpecialDict] = Queue()
Example(q1)
```

Now, to my knowledge, nothing about this breaks PEP conformance and I can't do `list1: Queue[SpecialDict]` because that gives `TypeError: 'method' object is not subscriptable`.

Error log:
```
Traceback (most recent call last):
  File "/Users/Moosems/Desktop/test.py", line 8, in <module>
    class Example:
  File "/Users/Moosems/salve/test.py", line 9, in Example
    @beartype
     ^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/beartype/_decor/decorcache.py", line 77, in beartype
    return beartype_object(obj, conf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/beartype/_decor/decorcore.py", line 87, in beartype_object
    _beartype_object_fatal(obj, conf=conf, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/beartype/_decor/decorcore.py", line 136, in _beartype_object_fatal
    beartype_nontype(obj, **kwargs)  # type: ignore[return-value]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/beartype/_decor/_decornontype.py", line 182, in beartype_nontype
    return beartype_func(obj, **kwargs)  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/beartype/_decor/_decornontype.py", line 247, in beartype_func
    func_wrapper_code = generate_code(bear_call)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/beartype/_decor/wrap/wrapmain.py", line 118, in generate_code
    code_check_params = _code_check_args(bear_call)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/beartype/_decor/wrap/_wrapargs.py", line 334, in code_check_args
    reraise_exception_placeholder(
  File "/usr/local/lib/python3.12/site-packages/beartype/_util/error/utilerrraise.py", line 138, in reraise_exception_placeholder
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/local/lib/python3.12/site-packages/beartype/_decor/wrap/_wrapargs.py", line 189, in code_check_args
    hint = sanify_hint_root_func(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/beartype/_check/convert/convsanify.py", line 178, in sanify_hint_root_func
    hint = reduce_hint(
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/beartype/_check/convert/convreduce.py", line 210, in reduce_hint
    hint = _reduce_hint_cached(hint, conf, exception_prefix)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/beartype/_util/cache/utilcachecall.py", line 250, in _callable_cached
    raise exception
  File "/usr/local/lib/python3.12/site-packages/beartype/_util/cache/utilcachecall.py", line 242, in _callable_cached
    return_value = args_flat_to_return_value[args_flat] = func(
                                                          ^^^^^
  File "/usr/local/lib/python3.12/site-packages/beartype/_check/convert/convreduce.py", line 367, in _reduce_hint_cached
    hint = hint_reducer(  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/beartype/_util/hint/pep/utilpepreduce.py", line 96, in reduce_hint_pep_unsigned
    die_unless_hint(hint=hint, exception_prefix=exception_prefix)
  File "/usr/local/lib/python3.12/site-packages/beartype/_util/hint/utilhinttest.py", line 99, in die_unless_hint
    die_unless_hint_nonpep(hint=hint, exception_prefix=exception_prefix)
  File "/usr/local/lib/python3.12/site-packages/beartype/_util/hint/nonpep/utilnonpeptest.py", line 203, in die_unless_hint_nonpep
    raise exception_cls(
beartype.roar.BeartypeDecorHintNonpepException: Method __main__.Example.__init__() parameter "list1" type hint <bound method BaseContext.Queue of <multiprocessing.context.DefaultContext object at 0x10cc0da30>> either PEP-noncompliant or currently unsupported by @beartype.
```

Beartype says however that this either breaks PEP compliance or is unsupported. I believe its the latter. Love the project and the work you do!

**Comment by leycec** [comment]
*...heh.* More non-standard mostly undocumented type hints, huh? No problem. @beartype chews up non-standard mostly undocumented type hints for breakfast. It turns out [everyone else is confused about `multiprocessing.Queue[...]` type hints](https://github.com/python/typeshed/issues/4313), too. Indeed, [it looks like this probably effects a constellation of interrelated non-standard mostly undocumented type hints that scare everybody](https://github.com/python/cpython/pull/99511) – including:

* `multiprocessing.Queue[...]` type hints.
* `multiprocessing.SimpleQueue[...]` type hints.
* `queue.Queue[...]` type hints.
* `queue.SimpleQueue[...]` type hints.

It seems likely that the `multiprocessing` variants are "simple" aliases of their corresponding original `queue` types. Moreover, if I'm reading the [official `queue` documentation](https://docs.python.org/3/library/queue.html) correctly, then **@beartype has no means of deeply type-checking `queue` types.**

Kinda unfortunate, but what can you do? The most @beartype can do here is shallowly type-check that `queue` types are of the expected classes; @beartype can't actually peek inside the items queued in a `queue` type without destroying that queue. This is probably by design to ensure that queues are safeguarded against multithreading race conditions. Still...

Kinda unfortunate. Let's do our best!

> @beartype: *We do our best even when that doesn't amount to much.*

**Comment by leycec** [comment]
**...hoh, boy.** So, I just spelunked (i.e., looked) into this. I have good news and I have bad news.

But first the **tl;dr.** Ain't nobody got the time to read all this madness. So, this is what you want to do:

```python
from beartype import beartype
from multiprocessing import Queue
from multiprocessing.queues import Queue as GenericQueue
from typing import TypedDict

class SpecialDict(TypedDict):
    pass

class Example:
    @beartype
    def __init__(self, list1: GenericQueue) -> None:
        self.list1: GenericQueue[SpecialDict] = list1

q1: GenericQueue[SpecialDict] = Queue()
Example(q1)
```

...which behaves as expected under the current stable `@beartype 0.18.5` release. Indeed, the above is the only usable way of typing what you want to type. The initial example you gave is improperly typed – but it's *not* your fault. Why? Because...

## Tell @Moosems What He's Won, Folks! ...yeah, it's bad news.

The bad news is that the `multiprocessing.Queue()` and `multiprocessing.SimpleQueue()` attributes are balls-crazy **methods.** Even though the official documentation states that both are classes, the official documentation lies. They're *not* classes. They have nothing to do with classes. They're standard pure-Python bound methods. Clearly, methods:

* Are *not* valid type hints.
* *Cannot* be subscripted.

Sadly, this means that @beartype is actually right about everything. From the perspective of runtime type-checking (*...so, @beartype*), PEP-compliance means "valid as type hints." Since `multiprocessing.Queue()` and `multiprocessing.SimpleQueue()` are invalid as type hints, they're PEP-noncompliant.

Moreover, since neither `multiprocessing.Queue()` or `multiprocessing.SimpleQueue()` are subscriptable, **no code anywhere should ever try doing stuff like `multiprocessing.Queue[SpecialDict]`.** Yeah, *sure*, technically that "works" <sup>...for certain specious definitions of "works"</sup> – but it shouldn't, because trying to subscript something that can't be subscripted is syntactically invalid. Those "type hints" don't actually run at runtime; they raise exceptions at runtime. If you were to automatically apply the `@beartype` decorator to the above code with an import hook like `beartype.claw.beartype_this_package()`, you'd immediately receive the same fatal exception as you've exhibited above:

```python
TypeError: 'method' object is not subscriptable
```

Why? Because @beartype import hooks necessarily evaluate type hints annotating global variable assignments (e.g., the `Queue[SpecialDict]` in `q1: Queue[SpecialDict] = Queue()`) at module importation runtime. Since @beartype import hooks are really the standard mode of operation for @beartype in 2024, the module you've defined above is **basically unimportable** by most @beartype users in 2024.

## But Wait! There's Good News.

The good news is twofold:

1. **Never use either the `multiprocessing.Queue()` or `multiprocessing.SimpleQueue()` methods as type hints.** Not even once. They're busted.
2. Instead, **only use the equivalent `multiprocessing.queues.Queue` and `multiprocessing.queues.SimpleQueue` types as type hints.** Unlike `multiprocessing.Queue()` and `multiprocessing.SimpleQueue()`, `multiprocessing.queues.Queue` and `multiprocessing.queues.SimpleQueue` are both valid type hints *and* subscriptable in the standard way.

Ideally, your initial example should be refactored to read:

```python
from beartype import beartype
from multiprocessing import Queue
from multiprocessing.queues import Queue as GenericQueue
from typing import TypedDict

class SpecialDict(TypedDict):
    pass

class Example:
    @beartype
    def __init__(self, list1: GenericQueue) -> None:
        self.list1: GenericQueue[SpecialDict] = list1

q1: GenericQueue[SpecialDict] = Queue()
Example(q1)
```

## But Wait! There *Is* Something @beartype Should Do Here.

@beartype can't fix the fact that `multiprocessing.Queue()` and `multiprocessing.SimpleQueue()` are balls-crazy methods rather than balls-normal types. That's CPython's fault, unfortunately. They should have resolved this issue decades ago, really. They didn't. My emoji weeps. :sob: 

@beartype *can* fix the exception it raises when confronted with either `multiprocessing.Queue()` or `multiprocessing.SimpleQueue()` as type hints. The current exception engenders confusion. Instead, @beartype should clarify this madness by explicitly informing funny guys with great personalities who are amazing devs such as yourself, @Moosems, that **only `multiprocessing.queues.Queue` and `multiprocessing.queues.SimpleQueue` should be used as type hints.**

Let's edit this feature request title for great justice.

**Comment by Moosems** [comment]
@leycec Thank you so so much for looking into that! Despite your claim "Ain't nobody got the time to read all the madness below" I actually found your explanation to be quite interesting and even a very enjoyable read 😄. Is `multiprocessing.Queue` a functional bros kind of function (how does it stay alive and with a changing state?)? Regardless, you're so so amazing and I can't thank you enough for your help and for this amazing project. Looking at the source code in my python download it shows `multiprocessing.Queue` as a class so maybe I'm misunderstanding how it works. Anyways, thank you again and I can't wait to hear how this story continues to unfold.
<img width="1078" alt="Screenshot 2024-06-15 at 9 32 03 AM" src="https://github.com/beartype/beartype/assets/95927277/f8eac3fb-a431-4370-ae16-14dc3acee7b9">

**Comment by Moosems** [comment]
I'm noticing that when asking for definition in my editor, both `multiprocesing.Queue` and `multiprocesssing.queues.Queue` led to the same place so maybe its only leading me to the definitions of the latter.

**Comment by Moosems** [comment]
Found it: https://github.com/python/cpython/blob/main/Lib/multiprocessing/connection.py#L510-L528

**Comment by Moosems** [comment]
```python
=================================== FAILURES ===================================
___________________________________ test_IPC ___________________________________

    def test_IPC():
>       context = IPC()

tests/test_ipc.py:7: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
<@beartype(salve_ipc.ipc.IPC.__init__) at 0x7fcf7cde60c0>:32: in __init__
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <salve_ipc.ipc.IPC object at 0x7fcf7cdf0d50>, id_max = 15000

    def __init__(self, id_max: int = 15_000) -> None:
        self.all_ids: list[int] = []
        self.id_max = id_max
        self.current_ids: dict[str, int] = {}
        self.newest_responses: dict[str, Response | None] = {}
        for command in COMMANDS:
   self.current_ids[command] = 0
   self.newest_responses[command] = None
    
        self.files: dict[str, str] = {}
    
>       self.response_queue: GenericClassQueue[Response] = Queue()
E       TypeError: type 'Queue' is not subscriptable

/opt/hostedtoolcache/Python/3.11.1/x[64](https://github.com/Moosems/salve/actions/runs/9539334939/job/26289541964?pr=20#step:4:65)/lib/python3.11/site-packages/salve_ipc/ipc.py:54: TypeError
=========================== short test summary info ============================
FAILED tests/test_ipc.py::test_IPC - TypeError: type 'Queue' is not subscriptable
========================= 1 failed, 1 passed in 0.18s ==========================
```

Runs fine locally but breaks on GH runners

**Comment by leycec** [comment]
*...heh.* `multiprocessing.Queue` internals, huh? Now we're *really* getting into the guts of the beast. To quote core CPython dev @JelleZijlstra at CPython PR python/cpython#99511

> `multiprocessing` scares me...

Preach, brother @JelleZijlstra. `multiprocessing` scares us all.

## The First Rule of Type Subscriptability Is...

**Wait.** What the heck is "type subscriptability," anyway? Okay. Let's back up.

Back when we were all younger and had muscles and smiled blissfully (albeit ignorantly), Python 3.9 implemented PEP 585. PEP 585 allowed core types (like `list` and `dict`) to be subscripted with child type hints (like the `typing.Union[int, str]` in `list[typing.Union[int, str]]`). That's type subscriptability. So far so good, right?

Clearly, not all types are subscriptable. Only types explicitly designed to be subscripted are subscriptable. The usual way this happens is with a crazy one-liner like `__class_getitem__ = classmethod(types.GenericAlias)`. It's best not to ask questions here. But the point I'm trying but failing to get to is that **type subscriptability doesn't happen automatically.** Type subscriptability only happens when you make it happen. So far so good, right?

Clearly, this implies that **most types are not subscriptable.** Although the general expectation is that more and more standard CPython types will become subscriptable over time, this is a gradual and frankly boring process that takes years and a great deal of pounding sand over CPython PRs.

In this case, the `multiprocessing.queues.Queue` class only became subscriptable with **Python 3.12.** This is why your GitHub Actions-based continuous integration workflow is failing. That workflow is running **Python 3.11,** which lacks support for subscripting `multiprocessing.queues.Queue`. Consider this output that is beyond boring:

```python
$ python3.12
>>> from multiprocessing.queues import Queue as GenericQueue
>>> print(GenericQueue[str])
multiprocessing.queues.Queue[str]  # <-- good. this is good, albeit boring.

$ python3.12
>>> from multiprocessing.queues import Queue as GenericQueue
>>> print(GenericQueue[str])
TypeError: type 'Queue' is not subscriptable  # <-- OMFG!!!!
```

## You Have Two Equally Awful Solutions Here

1. **Solution 1:** Drop support for Python < 3.12. Obviously, nobody's doing that. *Next!*
2. **Solution 2:** Conditionally support Python < 3.12 with a type alias resembling:

```python
from sys import version
from multiprocessing.queues import Queue as GenericQueue
from typing import TYPE_CHECKING

class SpecialDict(TypedDict):
    pass

# If either static type-checking *OR* this is CPython >= 3.12,
# subscript "GenericQueue" because we can. Just do it already!
if TYPE_CHECKING:
    GenericQueueOfSpecialDicts = GenericQueue[SpecialDict]
# Else, this is CPython < 3.12. We are now in the No Man's Land
# of Typing. In this case, avoid subscripting "GenericQueue". Ugh.
else:
    GenericQueueOfSpecialDicts = GenericQueue

class Example:
    @beartype
    def __init__(self, list1: GenericQueue) -> None:
        self.list1: GenericQueue[SpecialDict] = list1

q1: GenericQueue[SpecialDict] = Queue()
Example(q1)
```

Of course, I have tested nothing. Let's pretend that works.

Oh – and thanks so much for the kind words! It's a pleasure to dissect the CPython standard library on a workday that I should be dutifully working instead. *Why, oh why, did no work get done yet again!?* Oh, well. Let's just listen to music and pretend I did something. :notes: :headphones: :notes:

**Comment by Moosems** [comment]
It's quite unfortunate how messy multiprocessing is 😄.
