### ISSUE TITLE
Type check `Callable`'s

### ISSUE THREAD

**Issue by Moosems** [beartype/beartype#445]
`Callable`'s don't seem to be type checked, unfortunately.
```python
from beartype import beartype
from beartype.typing import Callable

@beartype
def foo(bar: Callable[[str], None]) -> None:
    bar("Hello world")

def baz() -> None:
    pass

foo(baz)
```

Traceback:
```python
Traceback (most recent call last):
  File "/Users/Moosems/Desktop/estensione/test.py", line 11, in <module>
    foo(baz)
  File "<@beartype(__main__.foo) at 0x10f4dcc20>", line 33, in foo
  File "/Users/Moosems/Desktop/estensione/test.py", line 6, in foo
    bar("Hello world")
TypeError: baz() takes 0 positional arguments but 1 was given
```

**Comment by leycec** [comment]
*...heh.* Just noticed that, huh? Yes. It's all true. @beartype still lies about many things. To see the exhaustive list of all things @beartype still lies about, please see our [BigData™ data sheet](https://beartype.readthedocs.io/en/latest/pep). Note that:

* The **"partial support"** column mostly means "@beartype only shallowly type-checks this thing."
* The **"full support"** column mostly means "@beartype only deeply type-checks this thing."

It's best not to read or believe ~~anything~~ everything I write. Still, [the anime-fuelled @beartype 0.19.0 changelog](https://github.com/beartype/beartype/discussions/441) quietly admits that the biggest offenders that have yet to be deeply type-checked are:

* **`Iterable[...]` type hints.** Not hard, so I claim. Just needs a bit of spit and polish, so I claim. I'm claiming lots of things without hard evidence here.
* **Callable type hints** (e.g., `collections.abc.Callable[...]`, `typing.Callable[...]`). Thankfully, BeartypeAI™ now provides a trivial `O(1)` one-liner for deeply type-checking *any* callable type hint `hint` against any arbitrary callable `func`:

  ```python
  def is_func_bearable(func: Callable, hint: object) -> bool:
      return is_subhint(infer_hint(func), hint)  # <-- lolbro
  ```

* **Type variables** (e.g., `typing.TypeVar('T')`. Still no idea how to dynamically generate efficient code type-checking type variables, honestly. It's feasible, but let's avoid thinking about this until there's *absolutely* nothing left to do. :sweat_smile: 

I actually had *no* idea how to even inefficiently deeply type-check `Callable[...]` type hints. But that was before `beartype.door.infer_hint()`. Now, I'm pretty sure it reduces to the trivial one-liner given above.

BeartypeAI™: *what doesn't that drunken dancing bear know?* :champagne: :bear:
