### ISSUE TITLE
Maximum recursion depth exceeded in `beartype==0.19.0`

### ISSUE THREAD

**Issue by femtomc** [beartype/beartype#447]
I just updated to `beartype==0.19.0` -- and all of a sudden I'm getting some recursion depth issues.

```python
        File "/Users/femtomc/Dev/genjax/.venv/lib/python3.12/site-packages/beartype/_util/func/arg/utilfuncarglen.py", line 210, in get_func_args_lens
          func = unwrap_func_all_isomorphic(func)  # type: ignore[arg-type]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/femtomc/Dev/genjax/.venv/lib/python3.12/site-packages/beartype/_util/func/utilfuncwrap.py", line 362, in unwrap_func_all_isomorphic
          if is_func_wrapper_isomorphic(func=func, wrapper=wrapper):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/femtomc/Dev/genjax/.venv/lib/python3.12/site-packages/beartype/_util/func/utilfunctest.py", line 1008, in is_func_wrapper_isomorphic
          get_func_args_nonvariadic_len(func_codeobj) ==
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/femtomc/Dev/genjax/.venv/lib/python3.12/site-packages/beartype/_util/func/arg/utilfuncarglen.py", line 438, in get_func_args_nonvariadic_len
          func_args_lens = get_func_args_lens(*args, **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      RecursionError: maximum recursion depth exceeded
```

It's possibly related to an error which `beartype` threw when I first re-tested my codebase on `0.19.0`:

```python
E   beartype.roar.BeartypeValeSubscriptionException: Callable <function Diff.static_check_tree_diff at 0x127d2c360> flexible argument count 0 != 1 (i.e., <function Diff.static_check_tree_diff at 0x127d2c360> accepts 0 rather than 1 positional and/or keyword parameters).
```

What is causing this error ... well, I have some `Is` type checks:

```python
Retdiff = Annotated[
    R,
    Is[Diff.static_check_tree_diff],
]
```

Here, `Diff.static_check_tree_diff` is a _static method_:

```python
@staticmethod
def static_check_tree_diff(v) -> bool:
    ...
```
but it does indeed accept a single argument, not 0.

**Comment by minmax** [comment]
I can't reproduce the bug, can you provide a minimal code example to reproduce the error?

```python
from typing import *
from beartype.vale import *

class C:
    @staticmethod
    def foo(v) -> bool:
        ...

class R:
    pass

Annotated[R, Is[C.foo]]
# typing.Annotated[__main__.R, beartype.vale.Is[C.foo]]
```

**Comment by femtomc** [comment]
Ah, `R` is a generic parameter, not a class.

**Comment by leycec** [comment]
**Ho, ho, ho.** Crazy inscrutable `RecursionError` blowing up, huh? I see that GenJAX is a private repo, which is understandable yet fills me with great sadness:

> Bayes3D is built on top of GenJAX, which is currently hosted in a **private Python package repository.**

Thanks so much to both of you for trying to deep dive to the bottom of this. I extrapolated @minmax's *wonderful* minimal working example (MWE) to make `R` generic, but @beartype 0.19.0 still blissfully accepts this without complaint: e.g.,

```python
from typing import *
from beartype.vale import *

R = TypeVar('R')

class C(object):
    @staticmethod
    def foo(v) -> bool: ...

Annotated[R, Is[C.foo]]
```

*Totally works.* Which is a bummer, actually. Something bad is happening, but we have no means of debugging that bad thing. That said...

## `beartype.vale.Is[...]` Doesn't Support `@static` Methods!?

**Woops.** That's super-bad. Whatever badness is going on which recursion here, the badness of `beartype.vale.Is[...]` no longer supporting `@static` methods is a *lot* badder. Sadly, `beartype.vale.Is[...]` never officially supported `@static` methods to begin with. Since this was never tested, I never even knew this broke (or that anybody wanted or needed this). Clearly, we should immediately do that.

Let's reprioritize this. In theory, I'll resolve this and push out a new @beartype 0.19.1 patch release in a few days. Also...

## Please Help Me Test @beartype 0.20.0 Release Candidates

I tried *really* hard to avoid breaking backward compatibility like this by [releasing a trio of @beartype 0.19.0 release candidates over the past several months](https://github.com/beartype/beartype/discussions/401#discussioncomment-10689661).

Likewise, I'll be releasing @beartype 0.20.0 release candidates in a few months. When I do, it would be *wonderful* if everyone could install those ahead of time to help avoid awful breakage like this. Thanks so much! After all, you all are the reason we QA. :smile_cat:

**Comment by leycec** [comment]
**Hmm.** Actually, I can't even reproduce the `@static` method issue. Seems fine, maybe?

```python
from typing import Annotated, TypeVar
from beartype import beartype
from beartype.vale import Is

R = TypeVar('R')

class C(object):
    @staticmethod
    def foo(v) -> bool:
        return bool(v)

@beartype
def muh_func(muh_arg: Annotated[R, Is[C.foo]]) -> Annotated[R, Is[C.foo]]:
    return muh_arg

print(muh_func(True))
print(muh_func(0))
```

...which prints:

```python
True
Traceback (most recent call last):
  File "/home/leycec/tmp/mopy.py", line 18, in <module>
    print(muh_func(0))
          ~~~~~~~~^^^
  File "<@beartype(__main__.muh_func) at 0x7f736f2253a0>", line 34, in muh_func
beartype.roar.BeartypeCallHintParamViolation: Function __main__.muh_func() parameter muh_arg=0 violates type hint typing.Annotated[~R, beartype.vale.Is[C.foo]], as int 0 violates validator beartype.vale.Is[C.foo]:
    False == beartype.vale.Is[C.foo].
```

Pretty sure there's something that both @minmax and I are missing here. I acknowledge that GenJAX is private, which puts a damper on things. But would you be able to supply some sort of a minimal working example (MWE) exhibiting either of these two issues, @femtomc. So sorry about this. Emoji cat is sad. :sob:

**Comment by femtomc** [comment]
I’ll deep dive and get a reproducer — sorry folks! Thanks for patience.
