### ISSUE TITLE
Create return tuple of annotated type hint

### ISSUE THREAD

**Issue by braniii** [beartype/beartype#47]
I just tried to use this amazing package for my new project. Sadly, I am struggling with the beartype validators. Defining types work like a charm, but once I combine multiple of them in a tuple beartype complains. Can anyone help me how to fix it? Thx :)

Here is a short example:
Tested with:

- Python 3.8
- Numpy 1.22
- Beartype 0.8.0 :tada: 
- typing_extensions 3.10.0

```Python
from typing import Tuple

import numpy as np
from beartype import beartype
from beartype.roar import BeartypeException
from beartype.vale import Is
from numpy.typing import NDArray
from typing_extensions import Annotated

Float1DArray = Annotated[
    NDArray[np.floating], Is[lambda arr: arr.ndim == 1],
]


@beartype
def func(a: Float1DArray) -> Float1DArray:
    return a


# this runs fine
func(np.arange(10).astype(float))


@beartype
def func2(a: Float1DArray) -> Tuple[Float1DArray, Float1DArray]:
    return (a, a)

# this sadly not
func(np.arange(10).astype(float))

```
This give me following error.
```Bash
Traceback (most recent call last):
  File "/home/***/anaconda3/envs/py3.8/lib/python3.8/site-packages/beartype/_util/func/utilfuncmake.py", line 150, in make_func
    exec(func_code, func_globals, func_locals)
  File "<string>", line 65
    isinstance(__beartype_pith_3 := __beartype_pith_1 := __beartype_pith_0[0], __beartype_object_139689216338944) and
                                                      ^
SyntaxError: invalid syntax

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 25, in <module>
    def func2(a: Float1DArray) -> Tuple[Float1DArray, Float1DArray]:
  File "/home/***/anaconda3/envs/py3.8/lib/python3.8/site-packages/beartype/_decor/main.py", line 244, in beartype
    func_wrapper = make_func(
  File "/home/***/anaconda3/envs/py3.8/lib/python3.8/site-packages/beartype/_util/func/utilfuncmake.py", line 174, in make_func
    raise exception_cls(
beartype.roar.BeartypeDecorWrapperException: @beartyped func2() wrapper unparseable, as @beartype generated invalid code with "SyntaxError: invalid syntax (<string>, line 65)":

(line 0001) def func2(
(line 0002)     *args,
(line 0003)     __beartype_func=__beartype_func,
(line 0004)     __beartype_raise_exception=__beartype_raise_exception,
(line 0005)     __beartype_object_139689218904560=__beartype_object_139689218904560,
(line 0006)     __beartype_object_139689167826912=__beartype_object_139689167826912,
(line 0007)     __beartype_object_139689216342720=__beartype_object_139689216342720,
(line 0008)     __beartype_object_139689216338944=__beartype_object_139689216338944,
(line 0009)     **kwargs
(line 0010) ):
(line 0011)     # Localize the number of passed positional arguments for efficiency.
(line 0012)     __beartype_args_len = len(args)
(line 0013)     # Localize this positional or keyword parameter if passed *OR* to the
(line 0014)     # sentinel value "__beartype_raise_exception" guaranteed to never be passed.
(line 0015)     __beartype_pith_0 = (
(line 0016)         args[0] if __beartype_args_len > 0 else
(line 0017)         kwargs.get('a', __beartype_raise_exception)
(line 0018)     )
(line 0019) 
(line 0020)     # If this parameter was passed...
(line 0021)     if __beartype_pith_0 is not __beartype_raise_exception:
(line 0022)         # Type-check this passed parameter or return value against this
(line 0023)         # PEP-compliant type hint.
(line 0024)         if not (
(line 0025)             (
(line 0026)                 isinstance(__beartype_pith_0, __beartype_object_139689216338944) and
(line 0027)                 # True only if this pith satisfies this caller-defined
(line 0028)                 # validator of this annotated.
(line 0029)                 (
(line 0030)                     # True only if this pith defines an attribute with this name.
(line 0031)                     (__beartype_pith_0_isattr_dtype := getattr(
(line 0032)                         __beartype_pith_0, 'dtype', __beartype_object_139689167826912))
(line 0033)                         is not __beartype_object_139689167826912 and
(line 0034)                     (__beartype_pith_0_isattr_dtype == __beartype_object_139689216342720)
(line 0035)                 )
(line 0036)             ) and
(line 0037)             # True only if this pith satisfies this caller-defined
(line 0038)             # validator of this annotated.
(line 0039)             (__beartype_object_139689218904560(__beartype_pith_0))
(line 0040)         ):
(line 0041)             __beartype_raise_exception(
(line 0042)                 func=__beartype_func,
(line 0043)                 pith_name='a',
(line 0044)                 pith_value=__beartype_pith_0,
(line 0045)             )
(line 0046) 
(line 0047)     # Call this function with all passed parameters and localize the value
(line 0048)     # returned from this call.
(line 0049)     __beartype_pith_0 = __beartype_func(*args, **kwargs)
(line 0050) 
(line 0051)     # Noop required to artifically increase indentation level. Note that
(line 0052)     # CPython implicitly optimizes this conditional away - which is nice.
(line 0053)     if True:
(line 0054)         # Type-check this passed parameter or return value against this
(line 0055)         # PEP-compliant type hint.
(line 0056)         if not (
(line 0057)             # True only if this pith is a tuple.
(line 0058)             isinstance(__beartype_pith_0, tuple) and
(line 0059)             # True only if this tuple is of the expected length.
(line 0060)             len(__beartype_pith_0) == 2 and
(line 0061)             # True only if this item of this non-empty tuple deeply
(line 0062)             # satisfies this child hint.
(line 0063)             (
(line 0064)                 (
(line 0065)                     isinstance(__beartype_pith_3 := __beartype_pith_1 := __beartype_pith_0[0], __beartype_object_139689216338944) and
(line 0066)                     # True only if this pith satisfies this caller-defined
(line 0067)                     # validator of this annotated.
(line 0068)                     (
(line 0069)                         # True only if this pith defines an attribute with this name.
(line 0070)                         (__beartype_pith_3_isattr_dtype := getattr(
(line 0071)                             __beartype_pith_3, 'dtype', __beartype_object_139689167826912))
(line 0072)                             is not __beartype_object_139689167826912 and
(line 0073)                         (__beartype_pith_3_isattr_dtype == __beartype_object_139689216342720)
(line 0074)                     )
(line 0075)                 ) and
(line 0076)                 # True only if this pith satisfies this caller-defined
(line 0077)                 # validator of this annotated.
(line 0078)                 (__beartype_object_139689218904560(__beartype_pith_1))
(line 0079)             ) and
(line 0080)             # True only if this item of this non-empty tuple deeply
(line 0081)             # satisfies this child hint.
(line 0082)             (
(line 0083)                 (
(line 0084)                     isinstance(__beartype_pith_4 := __beartype_pith_2 := __beartype_pith_0[1], __beartype_object_139689216338944) and
(line 0085)                     # True only if this pith satisfies this caller-defined
(line 0086)                     # validator of this annotated.
(line 0087)                     (
(line 0088)                         # True only if this pith defines an attribute with this name.
(line 0089)                         (__beartype_pith_4_isattr_dtype := getattr(
(line 0090)                             __beartype_pith_4, 'dtype', __beartype_object_139689167826912))
(line 0091)                             is not __beartype_object_139689167826912 and
(line 0092)                         (__beartype_pith_4_isattr_dtype == __beartype_object_139689216342720)
(line 0093)                     )
(line 0094)                 ) and
(line 0095)                 # True only if this pith satisfies this caller-defined
(line 0096)                 # validator of this annotated.
(line 0097)                 (__beartype_object_139689218904560(__beartype_pith_2))
(line 0098)             )
(line 0099)         ):
(line 0100)             __beartype_raise_exception(
(line 0101)                 func=__beartype_func,
(line 0102)                 pith_name='return',
(line 0103)                 pith_value=__beartype_pith_0,
(line 0104)             )
(line 0105) 
(line 0106)     return __beartype_pith_0
```

**Comment by leycec** [comment]
**Ugh.** Just when you think you've tested every rusty razor-sharp edge case, [a land shark suddenly rings the front doorbell](https://www.youtube.com/watch?v=p_NS2H55dxI).

Thanks so much for the detailed issue report, Dan the Man. We'll get everything sorted out for your exciting new project that will fundamentally change the world.

Given this and [your equally horrifying report that `numpy.typing.ArrayLike` type hints appear to be inducing infinite recursion from within the musty bowels of the `typing` module](https://github.com/beartype/beartype/issues/42#issuecomment-901068836), we'll *probably* kick out a new stable release tonight or tomorrow night. Thanks again! You rock the data science scene.

**Comment by braniii** [comment]
Thx, I am so hyped to use beartype :)

**Comment by leycec** [comment]
**Well.** *That* was a rough take. I'm drenched in salty, sweaty tears of desperation here in Canadian cottage country. I'm pretty sure I almost passed out from heat exhaustion while resolving this. And I'm pretty sure that means we now need an air conditioner.

What I'm trying to say is: this was non-trivial to fix. But this is critical, so I'll be pushing out a new minor **Beartype 0.8.1** release Friday evening just for this. I can't be exposing my beautiful userbase to non-human-readable syntax errors. This is 2021! Everyone deserves better.

Thanks again for that brain-bending type hint, @braniii. Sure, it made me want to punch a Bengal cat plushy until the stuffing comes out and my beautiful wife cries, "Why!? Why would you do that!?" But isn't that why we're all here, after all?

## Interesting Addendum

Did you know that, whereas chained assignments are syntactically valid, chained *assignment* expressions are syntactically invalid unless protected with parens?
    
```
>>> a = b =     'Mother*Teacher*Destroyer'  # <-- fine
>>> (a :=       "Mother's Abomination")     # <-- fine
>>> (a := (b := "Mother's Illumination"))   # <-- fine
>>> (a := b :=  "Mother's Illumination")    # <-- not fine
SyntaxError: invalid syntax
```
    
I didn't. The more you know, the less you know.

**Comment by leycec** [comment]
@braniii: **Beartype 0.8.1** has been forcefully ejected into the wild.

Let me know if you faceplant into any other stumbling blocks – however small – *or* think up any other genius-tier feature requests – however large. I feed on GitHub attention like the waddling raccoon family feasting on our tomato plants outside. :raccoon: :tomato:
