### ISSUE TITLE
deep type-checking support to core data structures and abstract base classes 

### ISSUE THREAD

**Issue by jondequinor** [beartype/beartype#53]
`beartype` currently only shallowly type-checks these type hints. It should, if at all possible, do this in constant time, runtime.

_This issue was copy-pasted from https://github.com/beartype/beartype/issues/7 — so see that issue for details. This issue tracks deep type-checking specifically._

**Comment by leycec** [comment]
**You're absolutely right,** of course. The long-term goalpost (which will never move) is for `beartype 1.0.0` to deeply type-check *all* PEP 484- and 585-compliant type hints in `O(1)` time.

Since that goalpost is barely even visible from where we currently stand, `beartype 1.0.0` and thus complete deep type-checking is unlikely to land this year. My ~~baseless delusion~~ optimistic expectation is that we'll get there by December, 2022. Until then, we'll use this issue to incrementally track how we're doing with each successive minor release leading up to `beartype 1.0.0`.

Keep the flame of quality assurance alive. May all your projects stay type-safe. :candle:

**Comment by leycec** [comment]
**Captain's Log, Stardate 2022.03.15.** `beartype 0.10.0` nudges us ever deeper into the deep end. @beartype now deeply type-checks *all* file handle protocols – including:

* `typing.IO` and `typing.IO[typing.Any]`, both matching any open file handle (regardless of encoding).
* `typing.IO[bytes]` and `typing.BinaryIO`, both matching any open binary file handle.
* `typing.IO[str]` and `typing.TextIO`, both matching any open plaintext file handle.

Let's see what `beartype 0.11.0` brings. I'm already strapped in, but even I don't know where we're going next! :racing_car:  :dash:

**Comment by leycec** [comment]
**Partially resolved by 9f227bd.** Our upcoming @beartype 0.18.0 release now **deeply type-checks all dictionary type hints in `O(1)` time.** To guarantee this extreme time constraint, @beartype currently only type-checks the first key-value pair of dictionaries. The price of speed is high. Still, this is a dramatic improvement over @beartype's prior approach of:

> "I didn't see nuffin'."

There are a *shocking* number of ways to annotate dictionaries. @beartype now supports all of them – except `typing.TypeDict`, which is kinda out of scope for this feature request. Also, I'm lazy. Notably, @beartype now supports *all*: 

* `dict[..., ...]` type hints.
* `collections.defaultdict[..., ...]` type hints.
* `collections.abc.Mapping[..., ...]` type hints.
* `collections.abc.MutableMapping[..., ...]` type hints.
* `collections.abc.OrderedDict[..., ...]` type hints.
* `typing.Dict[..., ...]` type hints.
* `typing.Mapping[..., ...]` type hints.
* `typing.MutableMapping[..., ...]` type hints.
* `typing.OrderedDict[..., ...]` type hints.

Let's kick this into high octane. Consider this minimal example integrating `@beartype` **+** nested dictionary type hints:

```python
from beartype import beartype
from collections.abc import Mapping, MutableMapping

@beartype
def go_bear(bear_bros_for_life: dict[
    int, Mapping[str, MutableMapping[bytes, bool]]]) -> None:
    print(bear_bros_for_life)

# This passes. A beautiful dictionary brings a tear to the eye.
go_bear({
    1: {
        'Beautiful bird;': {
            b'thou voyagest to thine home,': False,
        },
    },
})

# This fails! A horrible dictionary brings your app crashing to the ground.
go_bear({
    1: {
        'With thine,': {
            b'and welcome thy return with eyes': 1,
        },
    },
})
```

...which prints:

```python
{1: {'Beautiful bird;': {b'thou voyagest to thine home,': False}}}
Traceback (most recent call last):
  File "/home/leycec/tmp/mopy.py", line 21, in <module>
    go_bear({
  File "<@beartype(__main__.go_bear) at 0x7f75633de2a0>", line 91, in go_bear
beartype.roar.BeartypeCallHintParamViolation: Function __main__.go_bear() parameter
bear_bros_for_life={1: {'With thine,': {b'and welcome thy return with eyes': 1}}}
violates type hint dict[int, collections.abc.Mapping[str,
collections.abc.MutableMapping[bytes, bool]]], as dict key int 1 value dict key str
'With thine,' value dict key bytes b'and welcome thy return with eyes' value int 1
not instance of bool.
```

@beartype thus generates human-readable violation exceptions describing the exact path to the invalid key-value pair. Python QA will never be the same again. :muscle: :bear:

**Comment by leycec** [comment]
**Partially resolved by 38cfc61ce64c.** @beartype now deeply type-checks **reiterables** (i.e., collections satisfying the `collections.abc.Collection` protocol with guaranteed `O(1)` read-only access to *only* the first collection item). This includes *all* containers annotated by one or more of the following PEP 484- or 585-compliant type hints:

* `frozenset[...]`.
* `set[...]`.
* `collections.deque[...]`.
* `collections.abc.Collection[...]`.
* `collections.abc.KeysView[...]`.
* `collections.abc.MutableSet[...]`.
* `collections.abc.Set[...]`.
* `collections.abc.ValuesView[...]`.
* `typing.AbstractSet[...]`.
* `typing.Collection[...]`.
* `typing.Deque[...]`.
* `typing.FrozenSet[...]`.
* `typing.KeysView[...]`.
* `typing.MutableSet[...]`.
* `typing.Set[...]`.
* `typing.ValuesView[...]`.

The end of deep `O(1)` type-checking is now in sight, bear peeps. Testify! @beartype now deeply type-checks *almost* all possible type hints in `O(1)` time. Obvious exceptions include probably NP-complete shadow madness like:

* **Callable type hints** (i.e., `collections.abc.Callable[...]` and `typing.Callable[...]` type hints).
* **Type variables** (i.e., `typing.TypeVar(...)` type hints).

This is why @leycec will now sleep like bald sleeping beauty for a hundred years. It sounds like bliss, *because it is*.

![](https://media1.tenor.com/m/BzbYuCYSwAoAAAAC/polar-bear-spring.gif)
<sup>*pretty sure that bear ain't movin'*</sup>

**Comment by harshita-gupta** [comment]
@leycec forgive me for this potentially naive question, but can you remind us why `TypedDict` deep type-checking is out of scope for this feature request? Is that still something that you hope might be included in 1.0.0?

Thank you for your undying service to us python type enthusiasts. Some might argue that we fight a losing battle, but your resilience and wit keeps the paralysis of helplessness from eating me alive. :sob-salute:

**Comment by leycec** [comment]
**Oakland, CA!** *Represent.* I lived in south Berkeley for a time that now seems to reside outside time. Ah, to be young and inflamed with passionate tech ideas that went nowhere again! Life, truly. What a dream. I exhaustedly bicycled to work every day from south Berkeley to the Oakland BART station and then on to Walnut Creak. Anyone who has lived in or around Oakland now knows where I am going with this incomprehensible manologue, because...

That commute encapsulated **most of the most terrifying moments of my life.** I never knew visceral fear until I bicycled for the first time through Oakland in broad daylight. I still cherish those adrenaline-fuelled moments. The acrid sweat stinging my eyes as long-disused calf muscles forced themselves past the snapping point. The white-knuckled handlebar grip. The clenched jaw that felt like every molar was popping out of my mouth. "Please, decrepit dollar-store tricycle! Just hold up another five minutes!", I'd plead while devoutly praying to every ramshackle foreign deity I had ever done a Wikipedia deep-dive on.

*This is my story.* :smile: 

> @leycec forgive me for this potentially naive question

There are no naive questions. Only wonderful users.

> `TypedDict` deep type-checking is out of scope for this feature request...

**`TypedDict` deep type-checking is *definitely* in-scope.** I apologize profusely for any confusion by now grovelling on the floor. Anything that has yet to be deeply type-checked is *definitely* in-scope. This includes `TypedDict` and everything else that remains, which is still too much stuff.

Oh, *I get it.* I forgetfully omitted any reference to `TypedDict` above. That's the confusion, huh? Yeah. That makes sense. Personally, I do tend to forget about the existence of `TypedDict` altogether. I've never actually used a `TypedDict` myself in production. But I can see the allure – especially when coupled with [PEP 692 – Using `TypedDict` for more precise `**kwargs` typing](https://peps.python.org/pep-0692).

So, `TypedDict` is increasingly important for Pythonic `typing`. This means it will happen. It's just not necessarily a high priority, because I am biased towards vociferous outrage. The squeaky wheel gets the @beartype grease. Not many users have complained about @beartype's shoddy `TypedDict` support. Most recent complaints have surrounded:

1. [`collections.abc.Iterable[...]` and `typing.Iterable[...]` type hints](https://github.com/beartype/beartype/issues/344), which @beartype *still* fails to deeply type-check. I sigh. This is my next priority, because this is becoming shameful already.
2. [`@dataclasses.dataclass` type-checking on field assignment](https://github.com/beartype/beartype/issues/391). Supporting that would then transform @beartype into a full-fledged dataclass validation framework and thus a valid competitor to Pydantic. Watch out, Pydantic! The Bear is comin' for yer face. *Grrrrrrrr.* <sup><-- *scary stuff honestly*</sup>

Maybe `TypedDict` should be **number 3** on that list, huh? Sounds good. Make it so, ensign.

> Is that still something that you hope might be included in 1.0.0?

**That's exactly it.** In other words, there may never be a @beartype 1.0.0. :laughing: -> :sob: 

> Some might argue that we fight a losing battle...

I feel this argument in my colon.

> ...the paralysis of helplessness from eating me alive.

All I ask of you is that you never bicycle through Oakland. Life is too short, @harshita-gupta. Don't throw it away so casually. Only by bicycling through Oakland can one attain a certain knowledge of true helplessness and the gnawing fear that comes with the growing doom-storm on the horizon. The risks are high. The rewards are low.

Enlightenment do be like that.

**Comment by leycec** [comment]
**Partially resolved by e3882f341b158bcc6ad and 357df969b133018bc.** @beartype now deeply type-checks *all* **core concrete collections** (i.e., collections either builtin to Python *or* defined by the standard `collections` subpackage). This includes *all* containers annotated by one or more of the following PEP 484- or 585-compliant type hints:

* `collections.ChainMap[...]`.
* `collections.Counter[...]`.
* `collections.abc.ItemsView[...]`.
* `typing.Counter[...]`.
* `typing.ChainMap[...]`.
* `typing.ItemsView[...]`.

B-b-but... does anyone care? Does anyone actually *use* any of that esoteric `collections` stuff, anyway? Probably not. I'd never even heard of `collections.ChainMap` or `collections.Counter` before. Sure, they're nifty data structures... *I guess.* But nobody cares! I don't even specifically care about these data structures. I'm just here because my brain releases an addictive rush of dopamine whenever I deeply type-check something new. My brain no longer even particularly cares what I'm type-checking anymore. It's all the same to the brain. Good job, brain.

Aaaaaaand... we're all probably exhausted of this infinitely long decades-old issue at this point. All I can offer to succour your weary head is this pillow made of cats. May it aid you on your journey, QA traveller.

![](https://media.tenor.com/1ijK4BmKykYAAAAM/uncomfortable-awkward.gif)
<sup>*you can see the journey on the face*</sup>

**Comment by leycec** [comment]
**Partially resolved by 1a0250a41a368c0bc.** The upcoming <sup>*...i swear it!*</sup> @beartype 0.20.0 release now promises to deeply type-check:

* `collections.abc.Container[...]` and `typing.Container[...]` type hints.
* `collections.abc.Iterable[...]` and `typing.Iterable[...]` type hints.
* `collections.abc.Reversible[...]` and `typing.Reversible[...]` type hints.

This must be what they mean by a Christmas miracle.

![](https://media1.tenor.com/m/bOv5108n8qUAAAAd/eating-phil.gif)
<sup>*my face when the christmas miracle happened to me*</sup>

**Comment by pygarap** [comment]
@leycec, could you please list the types for which `beartype` currently performs only shallow type checking rather than deep type checking?

Including:
1. AsyncGenerator
2. AsyncContextManager
3. TypedDict
4. Annotated
5. Built-in parameterized generics
6. Union types
7. Required
8. NotRequired
9. TypeForm
10. Closed TypedDict
11. TypedDict with typed extra_items
