### ISSUE TITLE
[Bug] @beartype + `typing.TypeDict` + Python 3.14 = 😮 

### ISSUE THREAD

**Issue by KyleKing** [beartype/beartype#55]
I saw in #7 that TypedDict should be supported from 0.7.0 and [partial support](https://github.com/beartype/beartype/blob/42bb9079eade0cca7aeff184e522a160d72effd9/README.rst#compliance) has been in [beartype since 0.1.0](https://github.com/beartype/beartype/blob/42bb9079eade0cca7aeff184e522a160d72effd9/README.rst#features), but I'm running into errors with Python 3.7.12 and 3.9.7, so I'm not sure if this snippet should be working:

```python
# beartype==0.8.1

from beartype import beartype

try:
    from typing import TypedDict
except ImportError:  # For Python < 3.8
    from typing_extensions import TypedDict  # typing-extensions = "^3.10.0"

class Point2D(TypedDict):
    x: int
    y: int
    label: str

@beartype
def convert(point: Point2D) -> Point2D:
    return point

convert({'x': 1, 'y': 2, 'label': 'good'})
```

```shell
> python tmp.py                                                                                                                    ─╯
Traceback (most recent call last):
  File "/Users/kyleking/.pyenv/versions/3.9.7/lib/python3.9/site-packages/beartype/_util/cls/utilclstest.py", line 159, in die_unless_type_isinstanceable
    isinstance(None, cls)  # type: ignore[arg-type]
  File "/Users/kyleking/.pyenv/versions/3.9.7/lib/python3.9/typing.py", line 1956, in __subclasscheck__
    raise TypeError('TypedDict does not support instance and class checks')
TypeError: TypedDict does not support instance and class checks
```

Should beartype properly check TypedDicts? There were similar errors [found in Pydantic](https://github.com/samuelcolvin/pydantic/pull/2216) and [some notes here](https://mpkocher.github.io/). TypedDict can't be used with [isinstance by design](https://www.python.org/dev/peps/pep-0589/#using-typeddict-types). There is a [reference to tests for TypedDict](https://github.com/beartype/beartype/blob/afe505dc8d86a62e0410e602ea1b2dd3ca223f16/beartype_test/a00_unit/data/hint/pep/proposal/data_pep484.py#L13-L18), but they [don't appear to be present](https://github.com/beartype/beartype/blob/bd4626d2246ca4c5a15951dd19f9d2ff5277f8dd/beartype_test/a00_unit/data/hint/nonpep/proposal/_data_nonpep484.py#L80-L83)

And this isn't promising 😅 

https://github.com/beartype/beartype/blob/b7ab8b071430bd69768db0a05cfdde2d85841930/beartype/_data/hint/pep/sign/datapepsigns.py#L131

**Comment by leycec** [comment]
**...ohnoes.** You caught us red-handed – or honey-pawed, as it were. <sup>*badum ching*</sup>

A long time ago in a codebase far, far away, `@beartype` once shallowly type-checked `typing.TypedDict`... I *think,* anyway. Sadly, our inherent laziness coupled with aggressive release schedules means we kinda failed to properly test that.

Welp, this is awkward. Some recent release of `beartype` (*I am glaring at you,* `beartype 0.8.0`) quietly regressed that and broke both `typing.TypedDict` *and* `typing.NamedTuple`. I am now shaking my emaciated fists at my younger self, on whose behalf I now extend my most grievous apologies.

Thanks so much for the compassionate assistance, Master Kyle. Let's get this patched up for everyone and pretend this never happened! The sweat pouring off my forehead is real. :sweat: :sweat_drops:

**Comment by leycec** [comment]
@RomainBrault! My QA man! Python 3.14 alpha releases are out already, huh? Yikes. Guess it's time to bear up and bring the flamethrowers out. This is gonna be rough.

`TypedDict` breaking is probably the least of anyone's concerns under Python 3.14. @beartype *definitely* isn't ready for that prime time. Python 3.14 dramatically changes how annotations are stored and processed. Expect *major* breakage if you're throwing @beartype at Python 3.14. It'll probably take a few months for me to refactor everything to fully support Python 3.14.

Until then... this issue is still good to know. Thanks so much for the heads up. Let us resurrect this! QA Necromancy: "I invoke thee."

**Comment by leycec** [comment]
**Ha, ha!** Everything mysteriously works yet again with the magical combo of @beartype `0.22.0` and Python 3.14. Why? I... uhh, I have no idea. I probably fixed this half a year ago and then promptly forgot about it.

The River Lethe got nuthin' on @beartype. 😂

**Comment by SuperKenVery** [comment]
Does it really work for you?

This prints `Passed type check` for me, strage!
```python3
from typing import TypedDict

from beartype.door import die_if_unbearable


class TB(TypedDict):
    a: float


if __name__ == "__main__":
    test_sample = {"a": None}
    die_if_unbearable(test_sample, TB)
    print("Pased type check")

```

I'm using python 3.13.9 and beartype 0.22.6

**Comment by Glinte** [comment]
@SuperKenVery 

> **Brutally resolved!** In commit [342e5fc](https://github.com/beartype/beartype/commit/342e5fcd44ebeccd07ed27afccef0ba274e05e24) (and the upcoming `beartype 0.9.0` – it's any day now, we swear it on Bearzabubba), `@beartype` now shallowly type-checks both `typing.TypedDict` _and_ `typing_extensions.TypedDict` type hints as semantically equivalent to `collections.abc.Mapping[str, object]`.
> 
> Clearly, this is... _suboptimal._ But we can agree that something beats nothing. Well, conditionally depending on the exact nature of that something. So sometimes. And this is one of those times.
> 
> Thanks again for the thoughtful heads-up and _bearing_ hyuk hyuk with us here, Kyle the undisputed King of Parexel AI Labs. You deserve all the academic citations that the [@beartype](https://github.com/beartype) community has to give. Reference Kyle, everyone! He rocks that AI. 📝

 `@beartype` now shallowly type-checks both `typing.TypedDict` _and_ `typing_extensions.TypedDict` type hints as semantically equivalent to `collections.abc.Mapping[str, object]`.

**Comment by SuperKenVery** [comment]
@Glinte  Would you have a look at my code? I think it should raise an error as `a` is `None` rather than `float`. There is no nested TypeDicts, so shallow check should work in this case.

**Comment by Glinte** [comment]
typing.TypedDict => collections.abc.Mapping[str, object]

die_if_unbearable(test_sample, TB) => die_if_unbearable(test_sample, collections.abc.Mapping[str, object])

**Comment by SuperKenVery** [comment]
I appreciate your quick response, but I can't really understand it. By `=>` do you mean they are equivalent or should I replace that in my code?

**Comment by Glinte** [comment]
I am saying that yes it is not working properly because TypedDict is only partially supported. beartype consider them as equivalent even if TypedDict contains more information because beartype cannot yet use those information properly.

**Comment by leycec** [comment]
**I'm sorry!** Regretfully, @Glinte is right about everything like usual. @beartype currently reduces literally every `TypedDict` to simply `collections.abc.Mapping[str, typing.Any]`, which... is obviously trash. Full-blown deep type-checking of `TypedDict` is very much still on our event horizon and being actively tracked at venerable feature request #319. Has it really been two years? It has. 😭 

My priorities tend towards resolving critical compatibilities with popular third-party frameworks. Most recently, that's meant compatibility with FastMCP, LangChain, Celery, and now Gradio. The @beartype road map for a better future looks something like this:

* **@beartype `0.22.7`.** To be released tonight. Full Gradio compatibility. 💪 
* **@beartype `0.23.0`.** To be released in a month or two. Full compatibility with:
  * Alternate JIT-oriented Python interpreters like [PyPy](https://github.com/beartype/beartype/issues/324) and [GraalPy](https://github.com/beartype/beartype/issues/585).
  * The [`if TYPE_CHECKING:` anti-pattern for circular forward references](https://github.com/beartype/beartype/issues/477).
* **@beartype `0.24.0`.** To be released in six months or so. [Deep type-checking of both synchronous and asynchronous generators in `O(1)` constant-time](https://github.com/beartype/beartype/issues/589).
* **@beartype `0.25.0`.** To be released in a year or so. [Deep type-checking of `TypedDict` in something resembling `O(1)` constant-time](https://github.com/beartype/beartype/issues/319) and thus this issue! Rejoice! Yet, curse because we might all LLM-augmented cyborg VR cloud residents in a year. When you've been uploaded to The Cloud™, mere annoyances like @beartype and paying bills will simply be fond memories of your fleshy human past.

<sup>*...what am i even writing anymore*</sup>
