### ISSUE TITLE
[Bug] Variadic keyword arguments under beartype 0.10.0

### ISSUE THREAD

**Issue by leycec** [beartype/beartype#78]
Thankfully, we have yet to release `beartype 0.10.0`. Now, we know why.

During his [brutal campaign of pro-numeric optimization at `numerary`](github.com/posita/numerary), <sup>**...use it**</sup> @posita uncovered [severe breakage for `@beartype`-decorated callables passed variadic keyword arguments](https://github.com/beartype/beartype/issues/76#issuecomment-1000570436):

``` python
>>> from beartype import beartype
>>> @beartype
... def whoops(whoops_a, whoops_b: int = 0, whoops_c: str = "", **kw) -> None:
...     pass
Traceback (most recent call last):
  File "./bopo.py", line 5, in <module>
    def whoops(whoops_a, whoops_b: int = 0, whoops_c: str = "", **kw) -> None:
  File "/home/leycec/py/beartype/beartype/_decor/main.py", line 234, in beartype
    func_wrapper_code = generate_code(func_data)
  File "/home/leycec/py/beartype/beartype/_decor/_code/codemain.py", line 177, in generate_code
    code_check_params = _code_check_args(bear_call)
  File "/home/leycec/py/beartype/beartype/_decor/_code/codemain.py", line 379, in _code_check_args
    reraise_exception_placeholder(
  File "/home/leycec/py/beartype/beartype/_util/error/utilerror.py", line 202, in reraise_exception_placeholder
    raise exception.with_traceback(exception.__traceback__)
  File "/home/leycec/py/beartype/beartype/_decor/_code/codemain.py", line 301, in _code_check_args
    for arg_meta in iter_func_args(
  File "/home/leycec/py/beartype/beartype/_util/func/arg/utilfuncargiter.py", line 892, in iter_func_args
    param_meta.name = args_name[args_name_index_curr]
IndexError: tuple index out of range
```

The sweat dripping from my festive Christmas paper hat is real.

**Comment by leycec** [comment]
**Resolved by d710a54...** and just in time for Christmas too, little Billy!
